### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by geometrikal** [Kinnara/ModernWpf#1]
Downloaded the project but it wouldn't run as it is missing the dependencies Windows, Windows.Foundation.FoundationContract and Windows.Foundation.UniversalAPIContract

I added them via this method https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/desktop-to-uwp-enhance

**Comment by Kinnara** [comment]
This is strange since the .winmd files are included in the project in the current version. Did you clone/download the latest version?

**Comment by geometrikal** [comment]
@Kinnara I cloned it maybe a week ago. Just deleted and recloned the repo and it works now, thanks for that.
