### ISSUE TITLE
How to set up a border around listview?

### ISSUE THREAD

**Issue by Coke21** [Kinnara/ModernWpf#10]
Hi, I have a listview:
```
                <ListView Width="200" Height="200" Style="{StaticResource {x:Static GridView.GridViewStyleKey}}" BorderThickness="1.000001" ItemsSource="{Binding Items}">

                    <ListView.View>
                        <GridView>
                            <GridViewColumn Header="Description:" DisplayMemberBinding="{Binding Description}"/>
                            <GridViewColumn Header="X:" DisplayMemberBinding="{Binding X}" />
                            <GridViewColumn Header="Y:" DisplayMemberBinding="{Binding Y}" />

                        </GridView>
                    </ListView.View>

                </ListView>
```
As you can see, I tried `BorderThickness="1.000001"` but it didn't work.
Also, I tried using `ui:TitleBar.IsIconVisible="True"` but the icon doesn't appear in the title bar, there's only space for it but it's empty. I set up my icon through my application's properties and I can see the icon in my Window's taskbar.

**Comment by Kinnara** [comment]
1. You also need to set the `BorderBrush` property for the border to be visible. The default value is `null`.
2. For now you'll need to set the `Icon` property of the `Window`. Support for automatically using the assembly icon might get added in future versions.

**Comment by Coke21** [comment]
Alright, the first thing worked but the second didn't, for some reason it couldn't find the .ico file.  But I'm fine with it atm. Thank you for the quick response.

**Comment by Kinnara** [comment]
Update: The ability to use the assembly icon has been implemented and will be included in the next version.
