### ISSUE TITLE
Use Commands in Content Dialog

### ISSUE THREAD

**Issue by mrousavy** [Kinnara/ModernWpf#101]
How do I use the Commands in a Content Dialog?

I've tried using:

```cs
var addCommand = new RelayCommand<Project>(AddAction, (p) =>
{
    Console.WriteLine($"Can Execute? {p}");
    return p?.IsValid() == true;
});
var dialog = new ContentDialog()
{
    Content = new AddProjectViewModel(newProject),
    CloseButtonText = "Cancel",
    PrimaryButtonText = "Add",
    PrimaryButtonCommand = addCommand,
    PrimaryButtonCommandParameter = newProject,
    PrimaryButtonStyle = Application.Current.FindResource("AccentButtonStyle") as Style,
};
```
But the `addCommand`'s CanExecute and Execute methods never get fired.

I know I can get the result by awaiting the ShowAsync function, but that way I can't enable/disable the button like in a Command's CanExecute function. (Because the user should not always be able to click the primary button)

**Comment by mrousavy** [comment]
@Kinnara I see, But how am I supposed to conditionally enable the primary button? I want the button disabled until the form data the user entered is valid.

Thanks for the primary button tip!

**Comment by Insire** [comment]
I have the same problem. I can't seem to be able to keep the dialog from closing, when its content is invalid. Looks like i have to write my own Dialog-Window afterall.

**Comment by Insire** [comment]
this is what i came up with, to make it work:
```cs
        private void ContentDialog_PrimaryButtonClick(ContentDialog sender, ContentDialogButtonClickEventArgs args)
        {
            _viewModel.Validate();

            if (!_viewModel.HasErrors)
            {
                sender.Hide();
            }
            else
            {
                args.Cancel = true;
            }
        }
```
