### ISSUE TITLE
Icon List

### ISSUE THREAD

**Issue by nabeelio** [Kinnara/ModernWpf#102]
Hi,

Great project! I'm moving from my hodgepodge of MahApps/Material Design in XAML to just this. I'm trying to find the list of Icons, or being able to use a font from a `<Canvas .../>`. I'm looking at the list here:

https://docs.microsoft.com/en-us/windows/uwp/design/style/segoe-ui-symbol-font#icon-list

But that list doesn't seem to match up with the `<ui:SymbolIcon="">`. I tried including the font, but no luck:

```xml
<ui:FontIcon 
  FontFamily="pack://application:,,,/Resources/Segoe MDL2 Assets"
  FontSize="20"
  Glyph="E709" />
```

**Comment by ShankarBUS** [comment]
Try setting the **Glyph** in this format

1. From xaml : `&#x____;` like `&#xE709;`

2. From code : `\u____` like `\uE709`

For finding glyphs and icons I recommend **[Character Map UWP](https://www.microsoft.com/store/apps/9wzdncrdxf41?cid=storebadge&ocid=badge)** app, as it provides Glyph codes, symbol names, path data of those glyphs.

Have a nice day 🌞

**Comment by nabeelio** [comment]
That worked! That UWP app is great, thanks for that suggestion too. I was also missing the `#` before the font name. This worked, if anyone else is looking:

```xml
<ui:FontIcon 
  FontFamily="pack://application:,,,/Resources/#Segoe MDL2 Assets"
  Glyph="&#xE709;" />
```

**Comment by ShankarBUS** [comment]
Hey @nabeelio, You don't need to specify the font family, MDL2 assets is the **default** font family for FontIcon and SymbolIcon. If it's some other font then specify it. Why are you including it in your project while it is already installed on your system. You could've done like this :

```xaml
<ui:FontIcon 
  FontFamily="Segoe MDL2 Assets"
  Glyph="&#xE709;" />
```

or just this


```xaml
<ui:FontIcon Glyph="&#xE709;" />
```

**Comment by nabeelio** [comment]
Ah got it, I couldn't find which OS that was included with (I have some clients with < Windows 10), or if the one included just didn't have the icon I was looking for, since it wasn't there by name. Thanks!

**Comment by GF-Huang** [comment]
Does all these icons available before win10 (even if win7)?

**Comment by ShankarBUS** [comment]
No, you may have to manually install the Segoe MDL2 Assets font file on the target machine.

**Comment by GF-Huang** [comment]
Is there any solution install icon resources by NuGet like [Mahapp.Metro.IconPacks](https://github.com/MahApps/MahApps.Metro.IconPacks)?

**Comment by ShankarBUS** [comment]
No it is a font like a TTF font file

**Comment by GF-Huang** [comment]
Is there any icon font set built-in win7 also works in ModernWpf?

**Comment by ShankarBUS** [comment]
Hey @GF-Huang, there is no built in icon set for this in win 7, 8 or 8.1. The Segoe MDL2 Assets font was introduced with win 10, it's a normal font like Arial, consoles, Segoe UI, Times New Roman, etc. You can find the file in the `C:\Windows\Fonts\` folder or download it from the web.

**Comment by GF-Huang** [comment]
Understood, thank you.
