### ISSUE TITLE
Allow font-size to set for "ui:ControlHelper.Header"

### ISSUE THREAD

**Issue by nabeelio** [Kinnara/ModernWpf#103]
I apologize if I've missed this somewhere, but if a `FontSize` is set on a control, the `ui:ControlHelper.Header` will inherit it, which is usually fine, but it would be nice to be able to specify a separate font size for that. I've got some size 24 inputs. But no big deal, I've got a separate header now. I was just really confused wondering where it came from heh

**Comment by Kinnara** [comment]
You can also keep using `ui:ControlHelper.Header` and use a style to apply customizations to multiple controls of the same type:
```xaml
<Style TargetType="ComboBox" BasedOn="{StaticResource DefaultComboBoxStyle}">
    <Setter Property="FontSize" Value="20" />
    <Setter Property="ui:ControlHelper.HeaderTemplate">
        <Setter.Value>
            <DataTemplate>
                <TextBlock Text="{Binding}" TextWrapping="Wrap" FontSize="14" />
            </DataTemplate>
        </Setter.Value>
    </Setter>
</Style>
```

**Comment by nabeelio** [comment]
Ah good to know, thanks. I was trying to go through the code and see exactly which style I might have to modify but couldn't find it. Thanks! Might be a good snippet to have in the wiki.
