### ISSUE TITLE
moving a window

### ISSUE THREAD

**Issue by davidsisques** [Kinnara/ModernWpf#105]
Hello:
after creating a window I can resize but I can't move it

Thanks.

**Comment by milos12345** [comment]
If you have ExtendViewIntoTitleBar="True" then make sure the elements that extend into title bar area don't have WindowChrome.IsHitTestVisibleInChrome="True"

**Comment by ShankarBUS** [comment]
Can you share a repro of your window's xaml or code?

**Comment by davidsisques** [comment]
I think it was my mistake. I haven't managed to reproduce it and now it works fine.

Thanks
