### ISSUE TITLE
[Help] Thick border around window when using a software to protect my assembly

### ISSUE THREAD

**Issue by HadriMX** [Kinnara/ModernWpf#106]
Ok this is going to be a weird one.
I use [this software](https://www.eziriz.com/dotnet_reactor.htm) to protect my app assembly in order to make it harder to spy on our app code.
The problem is, after protecting the .exe file, the app main window now has a thick border (the border color changes with the app theme by the way) when maximized.
Before (unprotected)
![Screenshot (20)](https://user-images.githubusercontent.com/40123110/83908902-1b304c00-a725-11ea-918e-45e31c88624f.png)
After (unprotected)
![Screenshot (17)](https://user-images.githubusercontent.com/40123110/83908924-1ff50000-a725-11ea-9c17-d6e9a4a71bc1.png)

Another related fact is that localization doesn't work with the protected assembly, meanwhile the unprotected assembly does, since it picks up the windows language correctly.

I know these issues might be out of the scope, but any idea how to fix them?
Thank you very much for your work with this library, I love it.

**Comment by HadriMX** [comment]
Update: after doing a little bit of "UI debugging" with Snoop, I think it might have to do with ui:WindowHelper.IsAutoPaddingEnabled="True" somehow. Still don't know how to fix it.

**Comment by Kinnara** [comment]
Does this happen with the latest preview version?

**Comment by HadriMX** [comment]
I sent an email to their support and they fixed. Thank you for answering, you do a great work :D
