### ISSUE TITLE
NavigationView - don't navigate

### ISSUE THREAD

**Issue by nabeelio** [Kinnara/ModernWpf#107]
Is there a way to cancel a navigation? I'm using a `SelectionChanged` event, but what I want to do is "cancel" the navigation - for example, if someone is in the middle of editing something, and they click to a nav item, I want to (possibly) prompt them if they want to navigate away, but mainly, I want to cancel it. This is also the case where I have a button which triggers an event, and it's not a page that's "navigatable", so I don't want the little blue bar showing up that it's been navigated to

**Comment by Kinnara** [comment]
Does this help? https://stackoverflow.com/questions/53472413/uwp-unselectable-navigationviewitem-but-clickable

**Comment by nabeelio** [comment]
Thanks, that works. Good to know it follows those docs too. Had to add a new event for MouseDown to capture it but no issues there.

So I guess "cancellable" isn't a UWP behavior. I was looking through those docs and couldn't find anything.
