### ISSUE TITLE
Multiple (two) ContentDialogs needed

### ISSUE THREAD

**Issue by Lilium-Candidum** [Kinnara/ModernWpf#108]
Hello,

I need a second ContentDialog which opens in front of the current ContentDialog. Is there any way to do that? 

I have the user select some infos in the first ContentDialog and need the user to add more infos in the second one (those infos will be added to the infos in the first ContentDialog). In the end all gathered infos will be added to the UserControl which called the first ContentDialog.

Thank you

**Comment by ShankarBUS** [comment]
I guess this scenario is also not allowed in UWP, it will throw an [**InvalidOperationException**](https://github.com/Kinnara/ModernWpf/blob/761313f4d65fc7018596bfaf3c3db3d32a0c0fd9/ModernWpf.Controls/ContentDialog/ContentDialog.cs#L1075) saying 

> "Only a single ContentDialog can be open at any time."

One thing you can do is wait for the **first dialog** to close and show the **second dialog**.
What you're trying to do _(showing multiple content dialogs)_ is not a good UX.
see [this answer from SO](https://stackoverflow.com/a/35592947) to know how to handle the closing and opening

My suggestion is to use a **TabControl** or **Expander** to host theose additional infos.

**Comment by Lilium-Candidum** [comment]
Thank you, I will try that.
