### ISSUE TITLE
[Bug] NumberBox different default font size

### ISSUE THREAD

**Issue by nlogozzo** [Kinnara/ModernWpf#109]
By default, TextBoxs and DatePickers have a default font size of 14, however the NumberBox's font size seems smaller and I have to manually set it to 14

**Comment by Kinnara** [comment]
I'm not seeing this behavior in, for example, the [FluentRibbonSample](https://github.com/Kinnara/ModernWpf/tree/master/samples/FluentRibbonSample). Could you provide a repro?

**Comment by nlogozzo** [comment]
My Code:
`<fw:AcrylicWindow  x:Class="NickvisionApp.Views.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:ui="http://schemas.modernwpf.com/2019"
        xmlns:fw="clr-namespace:SourceChord.FluentWPF;assembly=FluentWPF"
        xmlns:ribbon="urn:fluent-ribbon"
        xmlns:local="clr-namespace:NickvisionApp.Views"
        mc:Ignorable="d" Title="NickvisionApp" Icon="../Resources/icon.ico" Width="1000" Height="800"
        TintOpacity=".9" AcrylicWindowStyle="NoIcon" WindowState="Maximized" Closing="WindowClosing">

    <Grid Background="Transparent">
        <ribbon:Ribbon HorizontalAlignment="Stretch" VerticalAlignment="Top">
            <ribbon:Ribbon.Menu>
                <ribbon:Backstage>
                    <ribbon:BackstageTabControl>
                        <ribbon:Button Header="Exit" ToolTip="Alt+F4" Icon="../Resources/exit.png" Click="MenuExit_Click"/>
                    </ribbon:BackstageTabControl>
                </ribbon:Backstage>
            </ribbon:Ribbon.Menu>

            <ribbon:RibbonTabItem Header="Help">
                <ribbon:RibbonGroupBox Header="Help">
                    <ribbon:Button Header="Changelog" LargeIcon="../Resources/changelog.png" Click="MenuChangelog_Click"/>
                    <ribbon:Button Header="About" LargeIcon="../Resources/about.png" Click="MenuAbout_Click"/>
                </ribbon:RibbonGroupBox>
            </ribbon:RibbonTabItem>
        </ribbon:Ribbon>

        <Grid Margin="0,122,0,24" Background="Transparent">
            <ui:NumberBox x:Name="numTest" HorizontalAlignment="Left" VerticalAlignment="Top" Margin="6,0,0,0" Width="300"
                          Header="Number Box" PlaceholderText="Enter number here"/>

            <TextBox x:Name="txtTest" HorizontalAlignment="Left" VerticalAlignment="Top" Margin="6,60,0,0" Width="300"
                     ui:ControlHelper.Header="Text Box" ui:ControlHelper.PlaceholderText="Enter text here"/>

            <DatePicker x:Name="dateTest" HorizontalAlignment="Left" VerticalAlignment="Top" Margin="6,120,0,0" Width="300"
                        ui:ControlHelper.Header="Date Picker" ui:ControlHelper.PlaceholderText="Select date"/>
        </Grid>

        <ribbon:StatusBar HorizontalAlignment="Stretch" VerticalAlignment="Bottom">
            <ribbon:StatusBarItem x:Name="statusReady" Content="Ready" HorizontalAlignment="Left" Margin="4,0,0,0"/>
        </ribbon:StatusBar>
    </Grid>
    
</fw:AcrylicWindow>
`

Which produces this:
![image](https://user-images.githubusercontent.com/17648453/85023229-71988400-b142-11ea-8e92-2ab84c94c625.png)

Notice how the numberbox's header text is smaller than the rest. If i add `FontSize="14"` property to the numberbox then the header matches the rest.

**Comment by Kinnara** [comment]
Ah, I see. Thanks for reporting. Will fix in the near future.

**Comment by nlogozzo** [comment]
👍 thanks
