### ISSUE TITLE
CheckBox margin?

### ISSUE THREAD

**Issue by Coke21** [Kinnara/ModernWpf#11]
I have a checkbox:
https://i.gyazo.com/6d77a333c8002bf45f97f99be47dd27a.png
You can see here that there is a strange margin above and below the checkbox. How can I overwrite the default checkbox's style so the top and bottom line will stay on the box? 
I tried to overwrite it in this way:
```
    <Window.Resources>
        <Style x:Key="MyStyle" BasedOn="{StaticResource DefaultCheckBoxStyle}"  TargetType="{x:Type CheckBox}">
            <Setter Property="???" Value="?"/>

        </Style>
    </Window.Resources>
```
However, I'm not sure what property should I overwrite. Thank you for your help.

**Comment by Kinnara** [comment]
The left (rectangle) part of the checkbox currently has a hardcoded height of 32. It's not ideal and could be improved to enable customization. As a workaround for now, `<Setter Property="Margin" Value="0,-6" />` seems to work.

**Comment by Coke21** [comment]
Yes, it partially works, however, now if there are two checkboxes next to each other and I click somewhere in-between them the second one gets activated and not the first one. Basically, the blue lines in the above gyazo are on top of the other checkbox. Is there any way to change VerticalAlignment to the center so the blue lines would stay on the box? Thank you for your help.

**Comment by Kinnara** [comment]
I tweaked the style so that now if you set `MinHeight` to 0 the checkbox won't have any extra margin/padding. You can update to the latest preview version to try it out.

**Comment by Coke21** [comment]
Oh yes, it works now. I really appreciate your quick response and help. Really love your library, keep up the good work.
