### ISSUE TITLE
Is there a way to put a menu in the titlebar area?

### ISSUE THREAD

**Issue by rerdavies** [Kinnara/ModernWpf#110]
I'm porting from mahapps. I currently have my menu in the titlebar area. But the ModernWpf titlebar intercepts all mouse events (presumably as Non-client mouse events).

Is there an easy way to remove the ModernWpf titlebar entirely, or some other way get a functional Menu on the titlebar?

**Comment by ShankarBUS** [comment]
1. `ui:Titlebar.ExtendViewIntoTitleBar="True"` in the window's xaml node

2. `WindowChrome.IsHitTestVisibleInChrome="True"` in the menu's xaml node

**Comment by rerdavies** [comment]
Thanks. That got me pointed in the right direction.  A more flexible approach:

  <Window 
    ...
      ui:Titlebar.ExtendViewIntoTitleBar="True" 
      >
      <WindowChrome.WindowChrome>
          <WindowChrome ResizeBorderThickness="5,0,5,5" CaptionHeight="0" />
       </WindowChrome.WindowChrome>

The principle advantage being that the previous suggestion disables system handling of window resizing on borders, and the window resize thumb (if any), whereas this version preserves it. (One also needs to place a view in the unused titlebar area to handle dragging of the window by the title bar, which is beyond the scope of this post)

Best regards.
