### ISSUE TITLE
FocusVisualStyle Should not visible by click for some controls. 

### ISSUE THREAD

**Issue by rasyidf** [Kinnara/ModernWpf#112]
This is small but noticeable glitch with the controls behavior, when creating checkbox / radio or something that clickable. the weird rectangle appars after clicked. and it's kinda ugly.

the behavior in ModernWPF is like this:

![ModernWPF](https://user-images.githubusercontent.com/28984914/84472602-ae332e00-acb1-11ea-986d-39a5760db533.gif)

For Comparison in the XAML Control Gallery (UWP) is like this:

![FluentUI](https://user-images.githubusercontent.com/28984914/84472754-fc483180-acb1-11ea-83ae-72cc1edf0146.gif)

## Discussion

I've made some research about this. that WPF clickable item, always call keyboard focus 
[here](https://social.msdn.microsoft.com/Forums/vstudio/en-US/ed6caee6-2cae-4db8-a2df-eafad44dbe37/mouse-focus-versus-keyboard-focus)

[the documentation](https://docs.microsoft.com/en-us/dotnet/api/system.windows.input.focusmanager.setfocusedelement?redirectedfrom=MSDN&view=netcore-3.1#System_Windows_Input_FocusManager_SetFocusedElement_System_Windows_DependencyObject_System_Windows_IInputElement_)

**Comment by Kinnara** [comment]
Does your system happen to have this setting enabled? WPF always shows the focus visual if this setting is on.

![image](https://user-images.githubusercontent.com/1617766/84499740-bc9b3d00-ace5-11ea-951c-0475a9c1a0d2.png)

**Comment by rasyidf** [comment]
I've deactivated this setting in win 10. 
![image](https://user-images.githubusercontent.com/28984914/84643219-b85e6200-af27-11ea-9a11-283bfa909434.png)

and it works, but really still wondering why.
