### ISSUE TITLE
How to modify TextBox context Menu?

### ISSUE THREAD

**Issue by XamDR** [Kinnara/ModernWpf#113]
Hi @Kinnara - I have a basic question about the TextBox's context menu. Is there a way to modify the context menu such as add more menu items or change the `InputGestureText` of an existing `MenuItem`?

For example, I would like to ~~add a `MenuItem` for the Redo command, and~~ modify the `InputGestureText` of the `SelectAll` command to match the behavior of the `TextBox`. In the image below:

<p align="center">
    <img alt="Context Menu" src="https://user-images.githubusercontent.com/35734934/84522418-3575a700-ac9c-11ea-9430-05c72a0be510.png"/>
</p>

The `MenuItem` "Seleccionar todo" (`SelectAll`) has the `InputGestureText` set to "Ctrl+E", but the `TextBox` itself uses the shortcut "Ctrl+A" to select all the text. ~~On the other hand, I would like to add a Redo `MenuItem` between "Deshacer" (Undo) and "Seleccionar todo".~~ Is it possible to do this without creating a custom `ContextMenu`?

**EDIT:** I realized that there is a `MenuItem` for the Redo command in the context menu, but still, I would be nice to be able to add another `MenuItem` like "Search with Bing", for example.

**Comment by Kinnara** [comment]
Adding a menu item should be pretty straightforward:
```xaml
<TextBox>
    <TextBox.ContextMenu>
        <ui:TextContextMenu>
            <MenuItem Header="Search with Bing" />
        </ui:TextContextMenu>
    </TextBox.ContextMenu>
</TextBox>
```
