### ISSUE TITLE
Menu Height override

### ISSUE THREAD

**Issue by pingu2k4** [Kinnara/ModernWpf#116]
Hi,
I  am trying to override the default menu and menu item height of 40. I can do it by, for each Menu and top level menu item setting their height explicitely, but I am looking to make them more compact by default without the explicitness.

I cant see a way to override this, though I could be missing something? Have tried addin a sys:double with a different value and the same key to a merged dict with XamlControlsResources, but that didn't work like I expected it would. Also there doesn't seem to be an override for it to make it more compact in the compact style.

**Comment by Kinnara** [comment]
There is a resource `MenuBarHeight` for menu height, unfortunately it's currently not overridable, You can override the default styles instead:
```xaml
<Style TargetType="Menu" BasedOn="{StaticResource DefaultMenuStyle}">
    <Setter Property="Height" Value="24" />
</Style>

<Style TargetType="MenuItem" BasedOn="{StaticResource DefaultMenuItemStyle}">
    <Style.Triggers>
        <Trigger Property="Role" Value="TopLevelHeader">
            <Setter Property="Height" Value="24" />
        </Trigger>
        <Trigger Property="Role" Value="TopLevelItem">
            <Setter Property="Height" Value="24" />
        </Trigger>
    </Style.Triggers>
</Style>
```
