### ISSUE TITLE
ModernWPF Scrollbar style vs UWP

### ISSUE THREAD

**Issue by slabrie-giro** [Kinnara/ModernWpf#117]
Hi,

I've been playing extensively with your toolkit and been wondering if there was any reason the toolbar style given in ModernWPF was different from the one found in UWP.

From what I've seen, UWP scrollbars are displayed quite thin till you hover over then, after which, they increase in size:
![image](https://user-images.githubusercontent.com/67075814/84950319-b8439b00-b0bc-11ea-9321-209a9834ab92.png)

I would also like to mention that I really appreciate your work on this project.

Thanks,
Simon

**Comment by ShankarBUS** [comment]
I was hitting the issue once, the auto hide is disabled by default you can enable it by setting `AutoHideScrollBars` to true.

Like this in the App.xaml : 

```xaml
<sys:Boolean x:Key="AutoHideScrollBars">False</sys:Boolean>
```
If you want follow the system's preference of auto hiding scrollbar take a look at [UISettingsResources.cs](https://github.com/Kinnara/ModernWpf/blob/24356c3d0ad97b5c519b49240a8c543816d277bb/samples/SamplesCommon/UISettingsResources.cs) it has the implementation of handling the system setting

**Comment by slabrie-giro** [comment]
Thanks @ShankarBUS for the answer! This pretty much do what I needed.

**Comment by Belim** [comment]
Hi,
great framework. Thanks for that!
Unfortunately this trick does not work for me yet

I've added `ui:ScrollViewerHelper.AutoHideScrollBars="True"` to MainWindow.xaml but the scrollbars remain permanently visible

How can this `<sys:Boolean x:Key="AutoHideScrollBars">True</sys:Boolean>` be app-wide implemented? Could you please specify it a little bit more.
