### ISSUE TITLE
Can't click HyperLink inside NavigationView

### ISSUE THREAD

**Issue by ShankarBUS** [Kinnara/ModernWpf#119]
**Describe the bug**
Can't click on hyperlink which is in a Page>Frame>NavigationView. It throws a `System.InvalidOperationException` saying **'System.Windows.Documents.Hyperlink' is not a Visual or Visual3D.**

**Steps to reproduce the bug**
1. Clone and build the [HyperlinkBug branch of ShankarBUS/ModernWpfTest](https://github.com/ShankarBUS/ModernWpfTest/tree/HyperlinkBug) repo
2. Run it and Navigate to the About page
3. Click on the hyperlink which says "Click this link"
 The error will thrown

**Expected behavior**
Clicking on hyperlink should work as expected

**Version Info**
NuGet package version: ModernWpf v0.9.0
.NET Core version: .NET Core 3.1.400-preview-015151

**Side Note**
If there are any mistakes in the way I did the project, please correct me. The error seems to go away if the AboutPage is shown at first but will happen when navigate to it again.

Hey @khdc,
Since you wanted to contribute, can help me with this one. I'm on a tight schedule this is giving me mental breakdown 😅

**Comment by Kinnara** [comment]
Looks like a bug in ItemsRepeater. A workaround is setting `Focusable` to `false`, or use HyperlinkButton.

**Comment by ShankarBUS** [comment]
Any timeframe when there will be release for this fix?
