### ISSUE TITLE
Cannot resolve brushes

### ISSUE THREAD

**Issue by dauthleikr** [Kinnara/ModernWpf#12]
Using .net core 3.0

I am getting some errors that styles could not be resolved:
![image](https://user-images.githubusercontent.com/5332935/69883233-7e9f7400-12d3-11ea-87da-556393d5ba92.png)

The app still builds and runs fine though.
My app.xaml looks like this:

```xaml
<Application x:Class="Hurace.RaceControl.App"
             xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:ui="http://schemas.modernwpf.com/2019"
             StartupUri="MainWindow.xaml">
    <Application.Resources>
        <ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>
                <ui:ThemeResources />
                <ui:XamlControlsResources />
            </ResourceDictionary.MergedDictionaries>

        </ResourceDictionary>
    </Application.Resources>
</Application>
```

Usage examples:
```xaml
<Button Style="{StaticResource AccentButtonStyle}" Content="Save" />
<Border BorderBrush="{DynamicResource SystemControlBackgroundBaseHighBrush}"> ...
```

Is there some way to get rid of the "errors"?

**Comment by Kinnara** [comment]
I also see these "errors" intermittently. [These steps](https://github.com/Kinnara/ModernWpf/wiki/Common-Tasks#enable-intellisense-for-xaml-resources) seem to help eliminate them or at least make them not appear as often.

**Comment by dauthleikr** [comment]
Works quite well, thanks for the hint. One small detail: The class is named Intelli**S**enseResources, but in the xaml it references a Intelli**s**enseResources (lowercase vs uppercase S).

**Comment by Kinnara** [comment]
Ah, good catch. Fixed. Thank you.
