### ISSUE TITLE
Applying style to custom DataGrid

### ISSUE THREAD

**Issue by sbc77** [Kinnara/ModernWpf#121]
Hi Kinnara,

Thanks for this project - is awesome.
I'm not fluent in WPF and I have troubles applying style to MyCustomDataGrid, which is directly derived from DataGrid.
How to do that?

Best regards,
Seba

**Comment by Kinnara** [comment]
Hi Seba. You can set `Style="{StaticResource {x:Type DataGrid}}"` on MyCustomDataGrid so that the derived DataGrid can "inherit" the style.

**Comment by sbc77** [comment]
Awesome - works!
Merci!
