### ISSUE TITLE
Use ModernWpf only on some controls

### ISSUE THREAD

**Issue by StefanKoell** [Kinnara/ModernWpf#122]
Hi,

I'm having a hard time to get ModernWpf to run only on certain controls. I am already using a 3rd party UI library which applies some global styles and there are conflicts when I add the lines 

                <ui:ThemeResources />
                <ui:XamlControlsResources />

to the app.xaml. When I move these to the window's or control's resource dictionary, I get the following exception:

> System.InvalidCastException: 'Unable to cast object of type 'System.Int32' to type 'System.Double'.'

Is there a way to use the controls/styles in parts of my app instead of applying them globally?
[ModernWpfNavView.zip](https://github.com/Kinnara/ModernWpf/files/4824971/ModernWpfNavView.zip)

**Comment by StefanKoell** [comment]
Did some more digging and found that these two methods:

        double GetPaneToggleButtonWidth()
        {
            return (double)(SharedHelpers.FindInApplicationResources("PaneToggleButtonWidth", c_paneToggleButtonWidth));
        }

        double GetPaneToggleButtonHeight()
        {
            return (double)(SharedHelpers.FindInApplicationResources("PaneToggleButtonHeight", c_paneToggleButtonHeight));
        }

in file *ModernWpf.Controls\NavigationView\NavigationView.cs* are the reason for the exception. The default value must be cast to double before passing it to FindInApplicationResources (they are both defined as int).

I'm wondering if FindInApplicationResources is the right approach here as this is forcing me to use the app.xaml and not the control's resource dictionary. Is this the case for other controls as well? Shouldn't the control always lookup resources in their own resource dictionary to enable local customization?

**Comment by Kinnara** [comment]
Unfortunately, currently ThemeResources has to been merged into App.xaml. Would it help to resolve the conflicts if you place the other library after ModernWPF?
```xaml
<ResourceDictionary.MergedDictionaries>
    <ui:ThemeResources />
    <ui:XamlControlsResources />
    <!-- 3rd party UI library -->
</ResourceDictionary.MergedDictionaries>
```

**Comment by Kinnara** [comment]
> Did some more digging and found that these two methods:
> 
> ```
>     double GetPaneToggleButtonWidth()
>     {
>         return (double)(SharedHelpers.FindInApplicationResources("PaneToggleButtonWidth", c_paneToggleButtonWidth));
>     }
> 
>     double GetPaneToggleButtonHeight()
>     {
>         return (double)(SharedHelpers.FindInApplicationResources("PaneToggleButtonHeight", c_paneToggleButtonHeight));
>     }
> ```
> 
> in file _ModernWpf.Controls\NavigationView\NavigationView.cs_ are the reason for the exception. The default value must be cast to double before passing it to FindInApplicationResources (they are both defined as int).
> 
> I'm wondering if FindInApplicationResources is the right approach here as this is forcing me to use the app.xaml and not the control's resource dictionary. Is this the case for other controls as well? Shouldn't the control always lookup resources in their own resource dictionary to enable local customization?

I believe it's the case for some controls, but not all. The reason it's this way is that NavigationView was directly ported from WinUI. I can remove the app resources requirement in this case, but there are other issues that prevent merging ThemeResources into a Window from working properly.

**Comment by StefanKoell** [comment]
Hi Kinnara,

thanks for your quick reply. Please check out the PR I just submitted:
https://github.com/Kinnara/ModernWpf/pull/123

I fixed the issue with the cast and also made sure the resource is looked up in the element's merged resource dictionary instead of the hardcoded app.xaml resource dict.

With these modifications, the control works properly in my scenario and I will explore soon if other controls can also be used this way.

Regarding your suggestion to place the 3rd party resources after the ModernWpf resources:
Unfortunately the 3rd party library I'm using (Actipro) doesn't have anything in the resource dictionary at all. I'm not sure how and when those styles and templates are applied since it's a commercial component library I chose mainly because of the syntax editor, docking framework and ribbon UI.

May I ask about the reason of this design decision to require the resources to place in the app.xaml? Shouldn't an element always look up resources in its own resource dictionary (which will be merged from the app.xaml down the hierarchy)?

Hardcoding the app.xaml resource dictionary lookup stips away the fundamental flexibility in WPF / styling to change/tweak the visuals and behavior throughout the app. If element lookup is implemented, the consumer of the package can decide whether or not to apply all styles and templates at the app level or on a control level. To be fair, I haven't looked at the code base in detail and cannot really speak for the rest of the library. Maybe there are situations where this might be necessary.

Anyhow, I'm happy to offer contributions and pull requests in case I stumble upon another situation like this - provided I'm able to fix it so that it would work both ways.

**Comment by Kinnara** [comment]
Hi Stefan,

Thank you very much for your contribution. About the requirement that resources need to be placed in App.xaml, it's mostly to support theming features such as element-level theme overriding. It has to do with how app-level resource dictionaries can differ from element-level resource dictionaries in behavior (WPF internals), and some features are simply not possible without ThemeResources in App.xaml. If you don't need these features, it should be possible to use this library without using the ThemeResources and XamlControlsResources classes, like what the [PowerShell sample](https://github.com/Kinnara/ModernWpf/blob/master/samples/PowerShellSample/MainWindow.xaml) does.

**Comment by StefanKoell** [comment]
I will open a new issue should I come across something similar going forward. This particular issue has been resolved with the PR. I will close this one.

Thanks again for the help.
