### ISSUE TITLE
Visual artifacts with .NET Core 3.1

### ISSUE THREAD

**Issue by realflight1** [Kinnara/ModernWpf#124]
I created a new WPF .NET Core project using VS2019 and followed the quick start instructions in the README. When running the application I get the following (GIF):

![modernwpfui_netcore](https://user-images.githubusercontent.com/29465282/85871128-f8c9a580-b79b-11ea-9c3d-e22a8d79150b.gif)

I am seeing similar issues with UseModernWindowStyle="False". Is .NET Core 3.1 supported? 

My code -

<details>
  <summary>App.xaml</summary>

    <Application x:Class="WpfApp1.App"
                 xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
                 xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
                 xmlns:ui="http://schemas.modernwpf.com/2019"
                 StartupUri="MainWindow.xaml">
        <Application.Resources>
            <ResourceDictionary>
                <ResourceDictionary.MergedDictionaries>
                    <ui:ThemeResources />
                    <ui:XamlControlsResources />
                </ResourceDictionary.MergedDictionaries>
            </ResourceDictionary>
        </Application.Resources>
    </Application>
</details>

<details>
    <summary>MainWindow.xaml</summary>

    <Window x:Class="WpfApp1.MainWindow"
            xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
            xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
            xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
            xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
            xmlns:local="clr-namespace:WpfApp1"
            mc:Ignorable="d"
            Title="MainWindow" Height="450" Width="800"
            xmlns:ui="http://schemas.modernwpf.com/2019"
            ui:WindowHelper.UseModernWindowStyle="True">
        <ui:SimpleStackPanel Margin="12" Spacing="24">
            <TextBlock Text="My first ModernWPF app" Style="{StaticResource HeaderTextBlockStyle}" />
            <Button Content="I am a button" />
            <Button Content="I am an accent button" Style="{StaticResource AccentButtonStyle}" />
        </ui:SimpleStackPanel>
    </Window>
</details>

**Comment by realflight1** [comment]
Closing this as the issue is caused by external software, in my case Sonic Suite.
For more details see https://github.com/dotnet/wpf/issues/707

**Comment by roceh** [comment]
Just for anyone who finds this as mentioned in https://github.com/dotnet/wpf/issues/707 you can set:

`
AllowsTransparency="True"
WindowStyle="None"
ui:WindowHelper.UseModernWindowStyle="True"
`

and that stops the corruption from occuring (at least for Nahimic DLL inject), some motherboard manufacturer install this with there realtek audio drivers. I've tested the audio drivers (Version 6.0.1.8496) for the ROG STRIX X370-F motherboard and it corrupts if the above is not set.
