### ISSUE TITLE
[Question] How to create a custom control library using this library with Light/Dark THEME support

### ISSUE THREAD

**Issue by ShankarBUS** [Kinnara/ModernWpf#126]
## [Question] How to create a custom control library using this library with Light/Dark THEME support

I'm creating a custom control library which uses this library and have some extra controls (like a toolkit).

But while doing so, I bumped on a issue where I can't support Light/Dark theme inside the library. For now, I have to define the theme specific resources in the ThemeResources in App.xaml which is not a good approach.

I tried to use ResourceDictionaryEx and its ThemeDictionaries but it's not working.

As a workaround I have to define theme specific resources in separate resource dictionaries and define this ⬇️ in the App.xaml of the application

```xaml
<ui:ThemeResources>
    <ui:ThemeResources.ThemeDictionaries>
        <ResourceDictionary x:Key="Light" ui:ThemeDictionary.Key="Light">
            <ResourceDictionary.MergedDictionaries>
                <ResourceDictionary Source="/MyLib;component/ThemeResources/Light.xaml"/>
            </ResourceDictionary.MergedDictionaries>
        </ResourceDictionary>

        <ResourceDictionary x:Key="Dark" ui:ThemeDictionary.Key="Dark">
            <ResourceDictionary.MergedDictionaries>
                <ResourceDictionary Source="/MyLib;component/ThemeResources/Dark.xaml"/>
            </ResourceDictionary.MergedDictionaries>
        </ResourceDictionary>

        <ResourceDictionary x:Key="HighContrast" ui:ThemeDictionary.Key="HighContrast">
            <ResourceDictionary.MergedDictionaries>
                <ResourceDictionary Source="/MyLib;component/ThemeResources/HighContrast.xaml"/>
            </ResourceDictionary.MergedDictionaries>
        </ResourceDictionary>
    </ui:ThemeResources.ThemeDictionaries>
</ui:ThemeResources>
```

I can't find any documentation regarding ThemeManager or ThemeResources.

So,
- How can I add theme support to my library?
- How can I add the theme specific resources inside Themes/Generic.xaml?
- How can I do it without requiring to add them in App.xaml?

**Comment by Kinnara** [comment]
Unfortunately the the workaround you're using is probably the best we can do for now. I'll try to think of a better way to support this scenario.

**Comment by blakepell** [comment]
I had a question similar to this, my thought pattern was along the lines of how can I provide a control in a control library that uses ModernWpf but caller doesn't have to know about it if they don't want to, I just give them a "hey here's your light/dark theme property as well as accent color property).  My solution (probably hacky) was to give my control the option to create the resource bits needed and add them into the Application resources.  That way, if the caller uses ModernWpf, great, they can add the stuff to `App.xaml` as they see fit and it works.  If they don't, I will add the resources (including the `ThemeResources`) to the Application from the control so the caller doesn't have to.  The automated way is probably fragile in regards to not having control on where those resources are slotted in, but then they just fallback to having to patch that stuff into the XAML themselves.
