### ISSUE TITLE
NumberBox compact mode popup doesn't disappear and is above all windows

### ISSUE THREAD

**Issue by geometrikal** [Kinnara/ModernWpf#13]
Using NumberBox in compact mode. v0.70

Clicking the arrows makes the arrow popup appear, but it does not disappear on enter or lost focus. In fact, it appears above all windows, e.g. if you alt-tab to something else.

**Comment by Kinnara** [comment]
Thanks for the report. It's fixed now and will be included in the next version, which I hope to publish soon. Pressing Enter commits the input but doesn't change the focus, therefore it's expected that the popup stays open.
