### ISSUE TITLE
控件一些设置

### ISSUE THREAD

**Issue by wf-soft** [Kinnara/ModernWpf#130]
为什么Style需要用这么多固定数值和动态资源来控制，用模板绑定不快乐吗？

**Comment by ShankarBUS** [comment]
Hey OP,

There are people who don't know other languages like Chinese?
Can you resubmit it in English?

Here's what he tries to say (translated using Google translate, may be inaccurate)

Title : **Some settings for control**
> Why does Style need to control it with so many fixed values and dynamic resources, and is it not happy to bind with templates?

**Comment by wf-soft** [comment]
does not have a signature we know about. Method GroupSearchKeyDown on target System.Object. Valid signatures are:Valid signatures are:

比如AutoSuggestBox事件也无法绑定Command

**Comment by wf-soft** [comment]
MVVM. I use "stylet",

**Comment by Kinnara** [comment]
There are indeed quite some hard-coded values being used. The primary reason is the majority of the styles are adapted from WinUI. As for the use of DynamicResource, it's mainly for supporting various theming features, including reacting to theme changes at runtime.
