### ISSUE TITLE
NumberBox padding doesn't apply any padding

### ISSUE THREAD

**Issue by pingu2k4** [Kinnara/ModernWpf#141]
I love what I have used this package for so far, so thank you (Also for jumping on the other issue I posted recently)

Padding currently doesn't apply correctly in NumberBox's. If I apply a corner radius of 10 it looks nice, but the Text in the textbox part is too close to the edge. I applied a padding thinking this would fix it (as it did for TextBoxed) but padding seems to have essentially no effect on NumberBox's.

**Comment by TroelsL** [comment]
Can reproduce here. A standard NumberBox doesn't appear to conform the the same dimensions as a TextBox, which I would expect. TextBox defaults to VerticalAlignment="Stretch", which is also the case for NumberBox, but while it takes of the expected space, it still renders as "Top".

See image for example. The two rightmost NumberBoxes are set to VerticalAlignment="Stretch" with a Margin of 0, and are on the same Row in a Grid.

![image](https://user-images.githubusercontent.com/8974441/90187294-d75b6200-ddb9-11ea-913c-d904df4a7a26.png)

**Comment by TroelsL** [comment]
Just to add to my previous comment: In order to make NumberBoxes align with TextBoxes, I had to apply the following styles:

        <Style TargetType="TextBox">
            <Setter Property="Margin" Value="1,2"/>
            <Setter Property="HorizontalAlignment" Value="Stretch"/>
            <Setter Property="VerticalAlignment" Value="Top"/>
        </Style>
        <Style TargetType="{x:Type controls:NumberBox}">
            <Setter Property="Margin" Value="1,0"/>
            <Setter Property="HorizontalAlignment" Value="Stretch"/>
            <Setter Property="VerticalAlignment" Value="Top"/>
        </Style>

It also seems strange that a different Margin is needed.

**Comment by Kinnara** [comment]
With this library and UWP/WinUI, it's often possible to override a XAML resource when it's not possible to set the property directly. In this case, you can use the following style to change the Padding of the inner TextBox:
```xaml
<Style TargetType="ui:NumberBox">
    <Setter Property="CornerRadius" Value="10" />
    <Style.Resources>
        <Thickness x:Key="TextControlThemePadding">12,5,6,6</Thickness>
    </Style.Resources>
</Style>
```
