### ISSUE TITLE
Proposal: Add MessageDialog from UWP

### ISSUE THREAD

**Issue by cafeed28** [Kinnara/ModernWpf#150]
### Summary

This proposal is to add MessageDialog function from [UWP](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/dialogs-and-flyouts/)

### Screenshots

**MessageDialog from UWP**
![image](https://user-images.githubusercontent.com/62172116/89105920-cb2ce780-d43e-11ea-8419-62876590d13d.png)

**Comment by nlogozzo** [comment]
That already exists. It's called a ContentDialog.
Here's an example:
`
using ModernWPF.Controls;

var dialog = new ContentDialog()
{
    Title = "Delete file permanently?",
    Content = "If you delete this file...",
    PrimaryButtomText = "Delete",
    CloseButtonText = "Cancel"
}
var result = await dialog.ShowAsync();
if(result == ContentDialogResult.Primary)
{
    Delete();
}
`

**Comment by bg117** [comment]
@nlogozzo Nope, that's different. A MessageDialog is the message box with a white background in UWP. It's a separate control from the ContentDialog.
