### ISSUE TITLE
Adding New Language (Persian)

### ISSUE THREAD

**Issue by ghost1372** [Kinnara/ModernWpf#152]
Hello, thank you for your ModernWpf
If you agree, I wanted to add Persian language
Do I need to translate anything other than this file?
https://github.com/Kinnara/ModernWpf/blob/master/ModernWpf/Resources/Strings.resx

**Comment by Kinnara** [comment]
Thank you. There is [another file in the ModernWpf.MahApps project](https://github.com/Kinnara/ModernWpf/blob/master/ModernWpf.MahApps/Resources/Strings.resx). For the existing languages I didn't actually translate anything—I try to get the translations from WinUI, and if they are not available, from the corresponding Windows language pack. This way we're consistent with Windows. The same can probably be done for Persian. I can do it if it's too much trouble. BTW is [this](https://github.com/microsoft/microsoft-ui-xaml/blob/master/dev/RatingControl/Strings/fa-IR/Resources.resw) a correct file for Persian 😅?

**Comment by ghost1372** [comment]
Oh, so that's it😀
Yes this file is correct, I can open a PR for this

**Comment by ShankarBUS** [comment]
- @Kinnara, Shouldn't this library support all the languages that WinUI supports?

- @ghost1372, Instead of adding support for just only one language, could you also add support for all the other languages supported by WinUI?

**Comment by ghost1372** [comment]
@ShankarBUS  I'm sorry, but I do not have enough time to do this There are too many languages (68), Also, adding all languages is not a good thing in my opinion Every file must be modified for each change. It is very time consuming Unfortunately, Microsoft did not put all the resources in one file and the resource created each control separately.

**Comment by milos12345** [comment]
Regarding languages, build creates a bunch of folders in bin\release with ModernWpf.resources.dll in them. Is there a way to prevent this?

**Comment by ghost1372** [comment]
@milos12345  you can write a PostBuild-Event in visual studio (Right Click Project and Properties\Build event) that delete extra folders each time you build
```
rd /s /q de
rd /s /q fr
```

**Comment by Kinnara** [comment]
> * @Kinnara, Shouldn't this library support all the languages that WinUI supports?

In theory, yes. In practice, adding a language can be time-consuming and error-prone, since currently the WinUI repo doesn’t contain all the required string resources. So initially I added only the languages that have corresponding string resources in .NET itself. The rest can be added as required.

**Comment by ShankarBUS** [comment]
Could that be possible once WinUI 3 is open sourced

**Comment by Kinnara** [comment]
> Could that be possible once WinUI 3 is open sourced

Very likely.

**Comment by Kinnara** [comment]
> Regarding languages, build creates a bunch of folders in bin\release with ModernWpf.resources.dll in them. Is there a way to prevent this?

The [SatelliteResourceLanguages](https://github.com/dotnet/docs/issues/18995) MSBuild property also seems to work.

**Comment by ShankarBUS** [comment]
@Kinnara 

> In theory, yes. In practice, adding a language can be time-consuming and error-prone, since currently the WinUI repo doesn’t contain all the required string resources. So initially I added only the languages that have corresponding string resources in .NET itself. The rest can be added as required.

If #202 were to be implemented, this would be trivial task!
