### ISSUE TITLE
Project Structure

### ISSUE THREAD

**Issue by ghost1372** [Kinnara/ModernWpf#154]
Hi, Please explain a little about the structure of the project if possible.

Why there are 2 projects as follows?
ModernWPF
ModernWPF.Controls
tnx

**Comment by ShankarBUS** [comment]
- The **ModernWpf** project is a just a library containing styles and themes for existing WPF controls

- The **ModernWpf.Controls** project has all the controls that are ported from WinUI (to reduce complexity and increase maintainability of code).
