### ISSUE TITLE
ListView Bug.

### ISSUE THREAD

**Issue by RaidenRipper** [Kinnara/ModernWpf#155]
Hello, I'm facing a weird bug with the ListView control, when I reach the bottom of the list all my CheckBox inside the DataTemplate become uncheck.
Thisis the XAML code.
![ListViewBug](https://user-images.githubusercontent.com/37519343/89712865-feed9d00-d969-11ea-9bad-5f6ffee8bd35.gif)

```xaml
<ui:ListView x:Name="LV_AUGMENTS" IsMultiSelectCheckBoxEnabled="False" IsItemClickEnabled="True" ItemClick="LV_AUGMENTS_ItemClick" IsSynchronizedWithCurrentItem="True">
<ui:ListView.ItemTemplate>
	<DataTemplate>
		<Grid Margin="6">
			<Grid.ColumnDefinitions>
				<ColumnDefinition Width="24" />
				<ColumnDefinition Width="*" />
			</Grid.ColumnDefinitions>
			<CheckBox x:Name="Augment" IsChecked="False" />
			<TextBlock Text="{Binding Name}" Margin="0, 5, 0, 0" Grid.Column="1" />
		</Grid>
	</DataTemplate>
</ui:ListView.ItemTemplate>
</ui:ListView>
```
I added gif so you can understand the issue.

**Comment by davidmoshecrow** [comment]
try to add VirtualizingPanel.VirtualizationMode="Standard"

**Comment by RaidenRipper** [comment]
Adding the ``VirtualizingPanel.VirtulizationMode="Standard"``, didn't work, the bug still persist.

**Comment by Kinnara** [comment]
Is the check status of the check box persisted anywhere (in the provided XAML there's only `IsChecked="False"`)?

**Comment by RaidenRipper** [comment]
> Is the check status of the check box persisted anywhere (in the provided XAML there's only `IsChecked="False"`)?

Yes, but the bug only happens in the second ListView, the other ListView has the same code but don't trigger the bug.
I decide to use a GridView to avoid this bug.
