### ISSUE TITLE
CommandBar SecondaryCommands CommandParameter passing null

### ISSUE THREAD

**Issue by nlogozzo** [Kinnara/ModernWpf#156]
I have a list element defined as `<MediaElement x:Name="mediaElement" HorizontalAlignment="Stretch" VerticalAlignment="Stretch" Margin="6,60,6,40"/>` that I am trying to pass as a command parameter. I also have SecondaryCommands defined as
```
<ui:CommandBar.SecondaryCommands>
                <ui:AppBarButton Label="Open Video" Icon="OpenFile" ToolTip="Ctrl+O" Command="{Binding OpenVideoCommand}" CommandParameter="{Binding ElementName=mediaElement}"/>
                <ui:AppBarButton Label="Close Video" Icon="Clear" ToolTip="Ctrl+W" Command="{Binding CloseVideoCommand}"/>
            </ui:CommandBar.SecondaryCommands>
```
However when I click the button the command parameter is null. If I were to move the AppbarButtons outside of SecondaryCommand and just into CommandBar the CommandParameter is passed the right way. How can I fix it were the command parameter is not passed as null when the button is defined in SecondaryCommands?

**Comment by Kinnara** [comment]
A simple way to solve this is to use `CommandParameter="{Binding Source={x:Reference mediaElement}}"`.

**Comment by ShankarBUS** [comment]
Could this probably be caused due to the command bar and it's secondary commands having different data context?

**Comment by Kinnara** [comment]
> Could this probably be caused due to the command bar and it's secondary commands having different data context?

It's mainly due to the secondary commands being in a different visual tree (inside a popup). I haven't checked if the DataContexts are the same, but in this case it's irrelevant because ElementName binding is used.

**Comment by nlogozzo** [comment]
@Kinnara 's fix worked. Thanks!
