### ISSUE TITLE
NavigationView ScrollViewer options

### ISSUE THREAD

**Issue by RaoHammas** [Kinnara/ModernWpf#161]
Hi. First of all thank you so much for this beautiful repo, really appreciate your work.
Secondly, as I'm using this in one of my project I'm facing an issue as shown in attached picture. The `NavigationView` implements a `ScrollViewer` automatically when there are more items or items are over-flowen.   

But, I see no way to disable this behavior or hide `ScrollBar`. Because in `Compact` mode of Navbar it doesn't look good. Or it should automatically be hidden when `NavigationView` is in Compact mode.  I have already tried to disable this using `ScrollViewer.VerticalScrollBarVisibility="Disabled"` but it doesn't work.

![ScrollBug](https://user-images.githubusercontent.com/16499626/91843592-72d04c00-ec6f-11ea-9269-8d27276a8b51.jpg)

**Comment by ShankarBUS** [comment]
See my previous comment - https://github.com/Kinnara/ModernWpf/issues/117#issuecomment-645713747

**Comment by RaoHammas** [comment]
> See my previous comment - [#117 (comment)](https://github.com/Kinnara/ModernWpf/issues/117#issuecomment-645713747)

Thank you  @ShankarBUS  It worked :)
