### ISSUE TITLE
Is there a mvvm  usercontrol like in AvalonEdit?

### ISSUE THREAD

**Issue by NiceLisan** [Kinnara/ModernWpf#163]
hopefully to see that in the ModerWpf

**Comment by davidrapan** [comment]
Hi, i kinda think its clear that this libs purpose is bring new Win Ui into old WPF which MS decided to burry deep underground. :) And that purpose is obviously fullfiled A+. But the main thing is that all u need for full MVVM u can already find build in .NETs WPF so there is no need for more "tools",, Anyway once more thx to author. rly great job. 👍
