### ISSUE TITLE
Build error with SDK-style project and .NET Framework 4.8

### ISSUE THREAD

**Issue by JVimes** [Kinnara/ModernWpf#164]
With an SDK-style .csproj that targets .NET Framework 4.8:

```csproj
<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ModernWpfUI" Version="0.9.1" />
  </ItemGroup>

</Project>
```

I get build error:

> MC1000	Unknown build error, 'Could not find assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. Either explicitly load this assembly using a method such as LoadFromAssemblyPath() or use a MetadataAssemblyResolver that returns a valid assembly.'

It builds if I target .NET Framework 4.6.1, but not 4.8.

Any ideas? Thank you.

**Comment by Kinnara** [comment]
Thanks for reporting, I can reproduce this issue. Don't really know the cause but a workaround seems to be adding `<Reference Include="netstandard" />` to the project file.

**Comment by JVimes** [comment]
Thank you, it built when I added `<Reference Include="netstandard" />`. It sounds like that reference [should have been](https://github.com/dotnet/standard/issues/542#issuecomment-349388295) included with .NET Framework, but isn't for 4.8 apparently.

If ModernWpfUI targets 4.8 and/or references the netstandard package, does that mean I don't have to reference netstandard in my app? If so, that would be a way to "fix" this error for users.

**Comment by Kinnara** [comment]
Good idea! The newly released v0.9.2 now references the netstandard assembly so library users don't have to reference it.

**Comment by JVimes** [comment]
Thank you @Kinnara but it did not work. If I upgrade to 0.9.2 and remove `Reference Include="netstandard" />`, I get:
```
System.Windows.Markup.XamlParseException
  HResult=0x80131501
  Message='Initialization of 'ModernWpf.ThemeResources' threw an exception.' Line number '10' and line position '18'.
  Source=PresentationFramework
  StackTrace:
   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at WpfApp1.App.InitializeComponent() in C:\Users\johnb\source\repos\WpfApp1\WpfApp1\App.xaml:line 1
   at WpfApp1.App.Main()

Inner Exception 1:
TypeInitializationException: The type initializer for 'ModernWpf.ThemeManager' threw an exception.

Inner Exception 2:
TypeInitializationException: The type initializer for 'ModernWpf.ColorsHelper' threw an exception.

Inner Exception 3:
FileNotFoundException: Could not load file or assembly 'System.Runtime.WindowsRuntime, Version=4.0.14.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies. The system cannot find the file specified.

Inner Exception 4:
FileNotFoundException: Could not load file or assembly 'System.Runtime.WindowsRuntime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies. The system cannot find the file specified.

```

**Comment by Kinnara** [comment]
My simple test app doesn't get this exception. Could you please share a repro project?

**Comment by JVimes** [comment]
Thank you, never mind. I did a git clean and it works.

Have you considered enabling [GitHub sponsorship](https://github.com/sponsors)? I'd like to sponsor.
