### ISSUE TITLE
Scrollbars permanently visible

### ISSUE THREAD

**Issue by Belim** [Kinnara/ModernWpf#165]
Hi,
great framework. Thanks for that!

Unfortunately this trick here https://github.com/Kinnara/ModernWpf/issues/117 does not work for me yet

I've added` ui:ScrollViewerHelper.AutoHideScrollBars="True" `to MainWindow.xaml but the scrollbars remain permanently visible

How can this `<sys:Boolean x:Key="AutoHideScrollBars">True</sys:Boolean>` be app-wide implemented? Could you please specify it a little bit more.

Thank you.

**Comment by ShankarBUS** [comment]
Add `ui:ScrollViewerHelper.AutoHideScrollBars="True"` to the scrollviewer that you want to target. (You can create your own style of scrollviewer based on the default one with auto hide scroll bars and apply it to all scrollviewers).

Add `<sys:Boolean x:Key="AutoHideScrollBars">True</sys:Boolean>` inside the `<Application.Resources>` node in App.xaml after the `<ui:XamlControlsResources/>

This will enable auto hide scroll bars without any additional work.

I'm not the author, I'm just a user of this library. You shouldn't create an issue just for this. You could've asked in the previous issue.

**Comment by Belim** [comment]
i've opened it because the issue was already closed and did not want to be overlooked :wink:
nevertheless I thank you :ok_hand: now i've got it

**Comment by ShankarBUS** [comment]
> i've opened it because the issue was already closed and did not want to be overlooked 😉

It's fine. But keeping open issues as low as possible will help the author track them.

> nevertheless I thank you 👌 now i've got it

I'm happy that you figured out how to fix it. There are too many infos specific to each app/libraries that we should learn before using them. If this library is documented well, it will be helpful to newcomers.

**Comment by Belim** [comment]
it's all good. i was almost embarrassed to ask because i knew it was simple but i was still in the early stages with wpf. 
thanks again for your quick reaction. so far the nicest framework i have seen :relaxed:

**Comment by ShankarBUS** [comment]
Yes this is a nice library indeed. I too am a newcomer to WPF (started about 8 months). I was also embarrassed to open an issue at first but how are we gonna solve it either without official help. But the next time if there is an exact issue open on a GitHub repo you could comment on that, people would still receive notifications on closed issues. Happy coding 👊✌️
