### ISSUE TITLE
NavigationView Pane background color

### ISSUE THREAD

**Issue by RaoHammas** [Kinnara/ModernWpf#166]
Hi, is there a way of changing `NavigationView` Pane `Background` and `Foreground` colors ? i think it's not possible in `UWP` or `WinUI` but it would be great if we can do it here in `WPF`. Can we ?  

![image](https://user-images.githubusercontent.com/16499626/92620703-60dc5200-f2dc-11ea-9d0c-4481bec4a5cf.png)

**Comment by ShankarBUS** [comment]
You **"can"** but there is no public API for that purpose. You have override the theme resources manually. This is also possible in UWP/WinUI.

If you already know about lightweight styling in WinUI, this would be easy for you (if you don't know, I recommend you to learn about it)

For example :

In the "App.xaml" or the resource dictionary of the window or the navigation view itself, you can override the background, foreground & etc.

```xaml
<SolidColorBrush x:Key="NavigationViewExpandedPaneBackground" Color="Red" />
```

See this file - [Light.xaml](https://github.com/Kinnara/ModernWpf/blob/1cc1d534a84e6fed18e7e1c268017eed5e68774b/ModernWpf/ThemeResources/Light.xaml#L824)
The resources starting with "NavigationView..." have to overriden for your specific purpose.

These resources could also be overridden from code but that would be hard.

**Comment by ShankarBUS** [comment]
And a personal question here

What charting/graph control do you use?

**Comment by RaoHammas** [comment]
> You **"can"** but there is no public API for that purpose. You have to override the theme resources manually. This is also possible in UWP/WinUI.
> 
> If you already know about lightweight styling in WinUI, this would be easy for you (if you don't know, I recommend you to learn about it)
> 
> For example :
> 
> In the "App.xaml" or the resource dictionary of the window or the navigation view itself, you can override the background, foreground & etc.
> 
> ```
> <SolidColorBrush x:Key="NavigationViewExpandedPaneBackground" Color="Red" />
> ```
> 
> See this file - [Light.xaml](https://github.com/Kinnara/ModernWpf/blob/1cc1d534a84e6fed18e7e1c268017eed5e68774b/ModernWpf/ThemeResources/Light.xaml#L824)
> The resources starting with "NavigationView..." have to be overriden for your specific purpose.
> 
> You are gonna have a lot of difficulties to change them in both themes (Light/Dark) & both view modes (Left/Top)
> These resources could also be overridden from code but that would be hard.

Yeah i actually got it. and achieved it exactly the way you have mentioned.  But thanks for your input :)

**Comment by RaoHammas** [comment]
> And a personal question here
> 
> What charting/graph control do you use?

ahaha. In past i've used alot https://lvcharts.net/ but this in the picture is Syncfusion's SfChart. And to be honest they are great. fully customizable.

**Comment by ShankarBUS** [comment]
@RaoHammas

> ahaha. In past i've used alot https://lvcharts.net/ but this in the picture is Syncfusion's SfChart. And to be honest they are great. fully customizable.

Thanks for the feedback, I too used LiveCharts WPF in my old projects but the project is now not actively maintained. That's why I wanted to know which WPF charting control you used so that I can move to use it.

So your issue is nearly fixed right?

Could you close this issue?

**Comment by RaoHammas** [comment]
@ShankarBUS i've found sfChart much better than LvCharts and they also have a really good community license.  yeah sure ill close . Thank you for your help :)
