### ISSUE TITLE
Proposal | Question - Enable the auto hide scrollbars option by default. Could it be done?

### ISSUE THREAD

**Issue by ShankarBUS** [Kinnara/ModernWpf#167]
This library has the in-built ability to auto hide scrollbars just as in UWP. But the option is disabled by default. This confuses a lot of new users and makes a simple task unsolvable/undiscoverable.

There are already multiple (3) issues regarding this one simple thing - i.e #117 #161 #165

Only enabling auto hide scrollbars won't be enough, there should also be a in-built way to listen to the system settings for auto hide scrollbars. This implementation could be seen in the sample app (I pointed this out in #117).

Just like this library listens to system theme/color changes, it should also listen to this setting.

This will provide consistency with UWP/WinUI.

@Kinnara, Could this be done? Do you consider doing this?

**Comment by Kinnara** [comment]
Great suggestion, thank you! This will be part of v0.9.2.

**Comment by ShankarBUS** [comment]
Shall I close this issue now @Kinnara?
