### ISSUE TITLE
Default AllowDrop setting for TreeViewItem

### ISSUE THREAD

**Issue by stevemonaco** [Kinnara/ModernWpf#170]
Hi, I recently ported one of my applications from MahApps to ModernWPF and had some troubles with previously working drag+drop behavior breaking for a TreeView using GongSolutions.WPF.DragDrop. I tested a standalone program with vanilla WPF vs ModernWPF and vanilla WPF TreeView worked out-of-the-box with GongSolutions whereas ModernWPF did not.

I continued to test ModernWPF by adding padding around the TreeView and the padding area supported drag+drop, but the nodes still did not. Finally, I looked through DefaultTreeViewItemStyle and [discovered that AllowDrop was set to False](https://github.com/Kinnara/ModernWpf/blob/master/ModernWpf/Styles/TreeView.xaml#L42). This was easily fixed on my end by creating a new style. I still suggest changing DefaultTreeViewItemStyle's AllowDrop setting to True to keep vanilla WPF behavior if this wasn't done intentionally for perf reasons. Thanks.

**Comment by Kinnara** [comment]
Thanks for bringing this up. That AllowDrop setter was merely carried over from the corresponding WinUI style, and should be removed as you said.

**Comment by Kinnara** [comment]
Resolved by cba42fb.
