### ISSUE TITLE
About Windows.SDK

### ISSUE THREAD

**Issue by wf-soft** [Kinnara/ModernWpf#176]
Hi! @Kinnara 

As a UI, it is used in the preview version Windows.SDK , up to 25mb, is it too heavy

**Comment by ShankarBUS** [comment]
I said saying this in the previous issue.

@Kinnara can't really do anything about this.

But .NET 5 is about to a get an incredible feature called [App Trimming](https://devblogs.microsoft.com/dotnet/app-trimming-in-net-5/), which will not only trim unnecessary dependencies (i.e unused *.dll files) but also trim the assembly contents (i.e. unused classes, modules, structs, enums, types & etc.) This feature is dangerous to use.

There are no workaround for this that could be provided @Kinnara. You have to trim as many unused code & dependencies on your side. This could be done while publishing your app.

**Comment by ShankarBUS** [comment]
@Kinnara, this issue is out of our area of expertise.

There's nothing we can do to reduce the assembly's size.

It all should be done on the app's side to reduce the package size as much as they can.

Thus, this issue could be closed and be labelled as `wont-fix`.

**Comment by Kinnara** [comment]
I agree with @ShankarBUS. BTW, Microsoft.Windows.SDK.NET.dll is much smaller when zipped, about 6 MB.
