### ISSUE TITLE
Interaction Trigger does not work for NumberBox 

### ISSUE THREAD

**Issue by PA256** [Kinnara/ModernWpf#178]
The Interaction Trigger seems to not work for NumberBox. The ValueChanged event will not trigger the Interactivity Command, although the ValueChanged event works in the code-behind.
            xmlns:i="http://schemas.microsoft.com/expression/2010/interactivity"
             xmlns:ui="http://schemas.modernwpf.com/2019"

<ui:NumberBox Value="{Binding Customer.Age, Mode=TwoWay, UpdateSourceTrigger=PropertyChanged}" >
<i:Interaction.Triggers>
<i:EventTrigger EventName="ValueChanged">
<prism:InvokeCommandAction Command="{Binding UpdateCommand}" />
</i:EventTrigger>
</i:Interaction.Triggers>
</ui:NumberBox>

**Comment by PA256** [comment]
For the Extended.Wpf.Toolkit it works with the exact same binding. It seems like the ModernWpf events are not being recognized properly by interactivity.

        private void NumberBox_ValueChanged(ModernWpf.Controls.NumberBox sender, ModernWpf.Controls.NumberBoxValueChangedEventArgs args)
        {

        }

        private void IntegerUpDown_ValueChanged(object sender, RoutedPropertyChangedEventArgs<object> e)
        {

        }

**Comment by Kinnara** [comment]
`i:EventTrigger` requires the event data to derive from `EventArgs`, which is an unnecessary constraint IMO. Anyway it shouldn't do any harm to derive `NumberBoxValueChangedEventArgs` from `EventArgs` so I'll make the change.

**Comment by PA256** [comment]
Sounds good. Thanks a lot!

**Comment by Kinnara** [comment]
Resolved by a23d5bc.
