### ISSUE TITLE
Close ContentDialog from WindowsParent

### ISSUE THREAD

**Issue by OrlandoNatsu** [Kinnara/ModernWpf#180]
I'm trying to use a Content dialog with a ProgressRing as an indicator while my application does a job. When you see to finish I want to close the ContentDialog but there is no Close() method. Or another way to close it other than from the same dialogue, only by secondary, primary and closing buttons. Can I programtically close a ContentDialog? Sorry for my english

**Comment by Kinnara** [comment]
The ContentDialog.Hide() method will do what you want.
