### ISSUE TITLE
The TextBox and ComboBox do not have the same Border Color, unlike UWP

### ISSUE THREAD

**Issue by alkbed** [Kinnara/ModernWpf#185]
Hi, 
My team and I noticed that the border of the TextBox is a lighter color than the border of the ComboBox. 
In the clip below, the controls without focus or hovering are different:
![image](https://user-images.githubusercontent.com/37509101/95864859-f5026480-0d33-11eb-9c76-8a56e32261ba.png)

In UWP, they seem to be the same (Normal (top) and ''Hot'' (bottom)):
![image](https://user-images.githubusercontent.com/37509101/95865084-3eeb4a80-0d34-11eb-8d05-97a9521c622e.png)

Was this intentionnal or is it something you will be fixing in the near future?
Thank you for this project and your time on this matter,
Alek B.

**Comment by Kinnara** [comment]
Indeed! I guess the lighter brushes were from the OS and I didn't notice WinUI have overridden them with darker ones. Should be fixed by ecf91800. Thanks for reporting.
