### ISSUE TITLE
Can't build samples

### ISSUE THREAD

**Issue by Andreln** [Kinnara/ModernWpf#186]
How to reproduce:
1. Clone or download repository.
2. Rebuild solution / Restore Nuget packages

I can't seem to build this out of the box, not sure what I am doing wrong.

Restoring nuget packages gives this error:
Error occurred while restoring NuGet packages: Invalid restore input. Missing required property 'Name'. Input files: C:\...\ModernWpf\ModernWpf.Controls\ModernWpf.Controls.csproj.

Rebuilding solution gives a lot of errors about restoring nuget packages.

Visual studio version:
Microsoft Visual Studio Community 2019
Version 16.7.5

**Comment by ssunbob** [comment]
This Project is using VS2019 in **Latest Preview Branch**. 
You can download the installer from official site : https://visualstudio.microsoft.com/vs/preview/ .

**Comment by FunJoo** [comment]
或许我和你有同样的情况出现，不过我的已经解决了
My solution:
Delete all the ";net5.0-windows10.0.18362.0" in <TargetFrameworks><TargetFrameworks/> in XXX.csproj
Powershell cd into project dir
Input "dotnet restore" Enter

**Comment by Andreln** [comment]
Thank you will try this out.
