### ISSUE TITLE
Build Error on .NET 5

### ISSUE THREAD

**Issue by PiotrekPKP** [Kinnara/ModernWpf#187]
After upgrading from .NET 5 preview 7 to .NET 5 RC 2 I'm getting this error on project build:
`Microsoft.NET.Sdk.targets(934, 5): [NETSDK1130] Referencing a Windows Metadata component directly when targeting .NETCoreApp,Version=v5.0 is not supported. Use the C#/WinRT projection tool (https://aka.ms/cswinrt) or a provided projection for this target.`
**To reproduce:
_Create WPF app using .NET 5, install newest version of ModernWpfUI (I'm getting error on older versions too), run build._**
Thanks in advance!

**Comment by ghost1372** [comment]
This is because of .NET 5
.NET 5 RC2 changed target framework name and is currently working properly in Visual Studio Preview 
So you need to install the latest preview version of Visual Studio
This is the new target framework name = **net5.0-windows**

for vs2019 you must enable the preview feature in settings (I did this but unfortunately the new project with .NET 5 fails. The best thing to do is to use the preview version.)

**Comment by PiotrekPKP** [comment]
I'm using proper target framework name and latest preview. It's because of that Nuget package.

**Comment by Kinnara** [comment]
The project needs to target net5.0-windows10.0.18362.0 or higher, since this library calls WinRT APIs. You can find [related documentation here](https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/desktop-to-uwp-enhance#net-5-preview-8-and-later-use-the-target-framework-moniker-option). The app will still be able to run on older versions of Windows.

**Comment by eltechnic0** [comment]
Now that NET 5 and VS2019 16.8 are out, this problem is still there and more relevant. Could you release a new version updated for this?

**Comment by rasyidf** [comment]
After targeting net5.0-windows10.0.18362.0 as you've said earlier throw another error:

> Referencing a Windows Metadata component directly when targeting .NETCoreApp,Version=v5.0 is not supported. Use the C#/WinRT projection tool (https://aka.ms/cswinrt) or a provided projection for this target.	 

Based on [this issue](https://github.com/dotnet/sdk/issues/13268) stated that

> We should update the error message (or perhaps just the link pointed at by https://aka.ms/cswinrt) to make it clear that the fix is to reference the Microsoft.Windows.CsWinRT NuGet package.

**Comment by ghost1372** [comment]
@rfloresarg just change targetframework to this:
`net5.0-windows10.0.18362.0`

**Comment by rfloresarg** [comment]
> net5.0-windows10.0.18362.0

Thanks for your help!

**Comment by skel35** [comment]
How can I still use ModernWpf in .NET 5 if I do not want to build separately for Windows 10.0.18362+, but for all Windows versions supported by .NET 5?

**Comment by ShankarBUS** [comment]
@skel35,

It's just the target SDK!

It will work older Windows  versions!

Try it out yourself 🙃.

**Comment by ghost1372** [comment]
> How can I still use ModernWpf in .NET 5 if I do not want to build separately for Windows 10.0.18362+, but for all Windows versions supported by .NET 5?

I created a custom version and I removed winRT dependency you can find it in my repo

**Comment by skel35** [comment]
Thanks, @ShankarBUS @ghost1372 !
I haven't used OS versions in target framework monikers before, so I misunderstood what it means.
I'll test this on an older OS when I can, but there should be no issues.
Here's a relevant doc for someone who might misunderstand it as I did: https://docs.microsoft.com/en-us/dotnet/standard/frameworks#os-version-in-tfms

**Comment by MilkyDeveloper** [comment]
>  just change targetframework to this:
> `net5.0-windows10.0.18362.0` or newer
Can reproduce, this fixes everything for me.

**Comment by Grendizr** [comment]
> I created a custom version and I removed winRT dependency you can find it in my repo

@ghost1372 Do you plan to merge this somehow in this repo ?

Regards

**Comment by ghost1372** [comment]
@Grendizr 
By removing WinRT, some features such as auto-setting the program theme and accent color will be lost, So I do not think the owner of this project will approve it

**Comment by mashbrno** [comment]
Isn't it possible to swap from WinRT to WinSDK?

**Comment by thebigsmileXD** [comment]
due to other dependencies i can't switch to net6 yet, WinSDK would be a much preferred solution to me as well
