### ISSUE TITLE
Can't build repo, gives error that System.Core v2.0.5.0 can'tbe found.

### ISSUE THREAD

**Issue by FransBouma** [Kinnara/ModernWpf#19]
Hi,

I'm trying to build the example app so I can get started with your library however I run into a problem, when I build the repository (after setting the global.json to sdk 3.1.100) (When building ModernWpf.Controls)

```
C:\Program Files\dotnet\sdk\3.1.100\Sdks\Microsoft.NET.Sdk.WindowsDesktop\targets\Microsoft.WinFX.targets(225,9): error MC1000: Unknown build error, 'Could not find assembly 'System.Core, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'. Either explicitly load this assembly using a method such as LoadFromAssemblyPath() or use a MetadataAssemblyResolver that returns a valid assembly.'  [C:\Users\****\Downloads\ModernWpf-0.7.3\ModernWpf.Controls\ModernWpf.Controls.csproj]
```
Which is weird, as it's not referenced anywhere. I check what it can be, and all I can find is old stuff related to windows XP, silverlight and portable libraries. 

You have any idea what to do to make the repository compile? I also tried to remove netcoreapp30 and target net452 or any higher version but same error. ...

TIA

**Comment by FransBouma** [comment]
Switching global.json's SDK to 3.0.100 fixes it, magically. 3.0.101, the one in the repo's global.json made the sln unloadable in rider/vs, so I bumped it up initially to 3.1.100, the latest GA version of the .net sdk.

So not a real bug, but perhaps a heads up for other people who have a load error on the repo and try to fix it by changing the global.json file to the latest GA release of the .netcore sdk :)

**Comment by Kinnara** [comment]
Thanks for sharing the details. The SDK version was set to 3.0.101 (latest version before 3.1) to work around dotnet/wpf#2274.

**Comment by FransBouma** [comment]
Yeah that looks like the exact same issue I ran into :) Anyway, things work now, your library is very helpful with my steps in WPF land (after 15 years of winforms development), keep up the good work!

**Comment by rstm-sf** [comment]
Hello!

The _global.json_ file does not allow me to load projects, and only moving it to _ModernWpf.SampleApp_ allows you to load projects and run samples

dotnet version 3.1.101
VS Version 16.4.3

Thank you!

**Comment by rstm-sf** [comment]
But I can start _ModernWpf.SampleApp_ only after _FluentRibbonSample_ has been started
