### ISSUE TITLE
Datagrid Binding with StringFormat clear cell

### ISSUE THREAD

**Issue by JM63** [Kinnara/ModernWpf#190]
Hi Kinnara,

Thank you for this great project

I'm using the datagrid object and it seems to work well, but something strange happens. 
When i move between cells using the keyboard the cell content disappears in the columns where i use the databinding with StringFormat (eg: Binding = "{Binding Price, StringFormat = C2} "or Binding =" {Binding Quant, StringFormat = N3} "), but if i use "{Binding="{Binding Price, StringFormat={}{0} €}" everything works fine.

![image](https://user-images.githubusercontent.com/20925684/97436098-5839ec80-1919-11eb-8199-0c3866c2b29f.png)

I have clear all visual studio 2019 temp files and reload the project, but the problem remains.

How can i solve that?

Best regards,

**Comment by Kinnara** [comment]
I can't seem to reproduce the issue. Could you please provide a repro project?
