### ISSUE TITLE
Question: Why is IconSource not supported in this library?

### ISSUE THREAD

**Issue by ShankarBUS** [Kinnara/ModernWpf#191]
For those who don't know about **IconSource**

[Windows.UI.Xaml.Contols.IconSource](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.iconsource) (present in UWP XAML)
[Microsoft.UI.Xaml.Controls.IconSource](https://docs.microsoft.com/en-us/uwp/api/microsoft.ui.xaml.controls.iconsource) (present in WinUI library)

> **IconSource** is similar to IconElement. However, because it is not a **FrameworkElement**, it can be shared.
[Source](https://docs.microsoft.com/en-us/uwp/api/microsoft.ui.xaml.controls.iconsource#remarks)

**IconSource** is itself useless without **IconSourceElement** (which inherits **IconElement** which in-turn inherits **FrameworkElement** -> **UIElement**).

As a **FrameworkElement** can have only one parent it can't be shared across controls. That's why MS employees made **IconSource** which is a **DependencyObject** and can be shared across multiple controls.

It's currently hard to keep track of icons across controls. As we can't share an **IconElement**, we have to do other workarounds such as storing the **glyphs (string)** in a static class and adding a **FontIcon** with the required **shared** glyph.

But the workaround will result in additional work to maintain properties other than **Glyph** consistent. We can't store **FontSize**, **Foreground** easily (we can define a common style though). Same applies to **PathIcon**, **SymbolIcon** and **BitmapIcon**.

These are the reasons that gave birth to **IconSource**.

Currently there are 4 subclasses of **IconSource**,
- **[BitmapIconSource](https://docs.microsoft.com/en-us/uwp/api/microsoft.ui.xaml.controls.bitmapiconsource)**
- **[FontIconSource](https://docs.microsoft.com/en-us/uwp/api/microsoft.ui.xaml.controls.fonticonsource)**
- **[PathIconSource](https://docs.microsoft.com/en-us/uwp/api/microsoft.ui.xaml.controls.pathiconsource)**
- **[SymbolIconSource](https://docs.microsoft.com/en-us/uwp/api/microsoft.ui.xaml.controls.symboliconsource)**

Why did you not port them too @Kinnara?

Are there are any specific reason not porting them?

Some **WinUI** 2.x controls (such as **TeachingTip**, **InfoBar** & etc) use **IconSource** which they use to create a **IconElement**s internally and use them.

Lack of this will block porting of **TeachingTip** or **InfoBar** in the future.

Could you port them? If not, I would like to contribute 😁.
Could you at least give me some guidelines and tips to do the port?

**Comment by ShankarBUS** [comment]
We can't implement **IconSourceElement** as its source code is not yet open.
But we don't need that BTW. **WinUI** uses a method to convert **IconSource** directly into its equivalent **IconElement**.
The method can be seen in [SharedHelpers](https://github.com/microsoft/microsoft-ui-xaml/blob/master/dev/dll/SharedHelpers.cpp) as [MakeIconElementFrom](https://github.com/microsoft/microsoft-ui-xaml/blob/da3964ea1f8d79032975d3820d3d269f200bf03b/dev/dll/SharedHelpers.cpp#L506).

Would mind if open a PR?

**Comment by Kinnara** [comment]
I believe the only reason is that it wasn't used by any controls in this library. Obviously we need to implement it in order to allow porting new controls from WinUI. And thanks a lot for creating the PR! I'll make sure to review it tomorrow.

**Comment by ShankarBUS** [comment]
> I believe the only reason is that it wasn't used by any controls in this library

That's a valid statement 😄.

 > And thanks a lot for creating the PR! I'll make sure to review it tomorrow.

I'm looking forward 😁.
