### ISSUE TITLE
Problem with MinWidth property of the ToggleSwitch

### ISSUE THREAD

**Issue by Nihilish** [Kinnara/ModernWpf#197]
Hello!

Me and my team have run into an issue with the ToggleSwitch. It seems whenever less than 154px are given to the view holding the ToggleSwitch (even if the switch itself takes up a lot less space than that), the focus rectangle doesn't get painted properly. 
![FocusError](https://user-images.githubusercontent.com/36556896/98034341-d5b3a000-1de4-11eb-9c49-8ab1bd0e2a73.png)
This can be fixed at runtime using Snoop by changing the MinWidth property of the nested grid within the control. 
![FocusErrorSnoop](https://user-images.githubusercontent.com/36556896/98034792-8cb01b80-1de5-11eb-86e6-c1aa9cf50d3b.png)

UWP doesn't behave the same way. Overriding **ToggleSwitchThemeMinWidth** locally doesn't seem to work. I think it would be appropriate if the ToggleSwitch itself had a property to set the MinWidth.

Thanks and keep up the good work! :)

**Comment by Kinnara** [comment]
Thanks for the detailed report. Let me make `ToggleSwitchThemeMinWidth` overridable.
