### ISSUE TITLE
NavigationView Scroll with a lot of Items

### ISSUE THREAD

**Issue by ghost1372** [Kinnara/ModernWpf#207]
Hi @ShankarBUS  
I have a NavigationView that has a lot of items (and Sub Items)
For example, 20 NavigationViewItem , each containing 100 NavigationViewItem
The problem is that if I try to scroll, the program slows down and scrolling is difficult
Is there a way to solve this problem?

**Comment by ShankarBUS** [comment]
This is not my repository and I'm not the author of this library 😅.

You have to ask @Kinnara (the author of **this** library).

I'm not a expert in NavigationView.
I don't know the internals of it.

@Kinnara ported NavigationView from WinUI.

They may know something.

**Comment by ghost1372** [comment]
@ShankarBUS  i know it but I asked you because you are very active in this repo😁
Thanks anyway👍

**Comment by ghost1372** [comment]
@Kinnara  Can you check this?
This seems to be a bug, The UWP version works without any problem with +200 items but With your library, items loading time is long and scrolling is very difficult

**Comment by Kinnara** [comment]
Hmm, I tried the following code and scrolling is just as sluggish with WinUI, if not more so. Scrolling performance can be improved by [using a custom non-virtualizing stack layout](https://github.com/Kinnara/ModernWpf/issues/111#issuecomment-642135614), but the initial opening of each item will be slower, especially when it has many sub items.
```cs
for (int i = 0; i < 20; i++)
{
    var item = new NavigationViewItem { Content = $"Item {i}" };
    for (int j = 0; j < 100; j++)
    {
        item.MenuItems.Add(new NavigationViewItem { Content = $"Sub item {j}" });
    }
    NavView.MenuItems.Add(item);
}
```

**Comment by ShankarBUS** [comment]
@Kinnara,

> I tried the following code and scrolling is just as sluggish with WinUI, if not more so.

But **Xaml Controls Gallery** works fine without any scroll lag in the NavView. It doesn't have 100 sub-items for each item though.

Anyways, are you're saying that this lag is unavoidable? Should we also file a clone of this issue on WinUI's repo?

**Comment by ghost1372** [comment]
> ```cs
> for (int i = 0; i < 20; i++)
> {
>     var item = new NavigationViewItem { Content = $"Item {i}" };
>     for (int j = 0; j < 100; j++)
>     {
>         item.MenuItems.Add(new NavigationViewItem { Content = $"Sub item {j}" });
>     }
>     NavView.MenuItems.Add(item);
> }
> ```

thank you non-virtualizing stack layout fixed my problem
