### ISSUE TITLE
Add Migration Guide for Net 5.0

### ISSUE THREAD

**Issue by rasyidf** [Kinnara/ModernWpf#208]
As big changes introduced into `.net5` that annoy some people like in #187. would it be great to add notes to migrating to `.net5` 
 
example:
Add package **Microsoft.Windows.CsWinRT** 
``` pwsh
Install-Package Microsoft.Windows.CsWinRT -Version 1.0.1
``` 

change target framework to **net5.0-windows10.0.18362.0** or higher like this:
``` xaml
...
<TargetFramework>net5.0-windows10.0.18362.0</TargetFramework>
...
```

and some notes for common workaround

**Comment by ShankarBUS** [comment]
You don't need to manually add package reference to CsWinRT.

Setting the target framework to `<TargetFramework>net5.0-windows10.0.18362.0</TargetFramework>` will automatically pull in the reference to CsWinRT and the Windows SDK!

That's it!

No annoying procedures as you said!
