### ISSUE TITLE
SimpleTimePicker (Dark theme) : OK et Cancel buttons are too dark

### ISSUE THREAD

**Issue by ghost** [Kinnara/ModernWpf#21]
Is it possible to have the OK et Cancel button White when using the dark theme ?

![image](https://user-images.githubusercontent.com/59298976/71918321-0e94d100-3150-11ea-88b6-87c80528aa8d.png)

**Comment by Kinnara** [comment]
These are white by default. I guess it might be related to something in your project. Could you post the relevant XAML or provide a repro? Below is a screenshot from the sample app:

![image](https://user-images.githubusercontent.com/1617766/71947245-4743b180-3207-11ea-9f14-68329c529c9b.png)
