### ISSUE TITLE
Two columns ahead of AppBarToggleButton and AppBarButton with Icon

### ISSUE THREAD

**Issue by bjit311** [Kinnara/ModernWpf#219]
Steps:
1. Add  AppBarToggleButton and AppBarButton with Icon in xaml below.
           <ui:AppBarToggleButton Label="AutoLogin" />
            <ui:AppBarSeparator />
            <ui:AppBarButton Label="Setting" Icon="Setting"/>
2. Launch app and tick the AutoLogin button.

Result:
Two columns ahead of AppBarToggleButton and AppBarButton with Icon
The tick and icon are not in the same column.

Expected:
The tick and icon is in the same column.

Note:
The issue doesn't reproduce if no Icon in the AppBarButton.

![image](https://user-images.githubusercontent.com/75471402/101136326-1d2d8600-3648-11eb-8a4a-c0c8c519109d.png)

**Comment by Kinnara** [comment]
This is by design because UWP/WinUI has the same behavior.
