### ISSUE TITLE
Multiple content dialogs overlap issue

### ISSUE THREAD

**Issue by niels9001** [Kinnara/ModernWpf#221]
Running into the following issue:

When opening a second content dialog from the first contentdialog the first dialog is on top of the second dialog.

Expected behavior:
- The first dialog closes so that the second dialog is only shown.

![DialogZIndex issue](https://user-images.githubusercontent.com/9866362/101282528-0cab1600-37d6-11eb-824f-4eba6b1d43f9.gif)

**Comment by ShankarBUS** [comment]
AFAIK the first popup is not a "ContentDialog".

It must be a flyout. The `ContentDialog` is designed to be shown within the root of the window. While the `Flyout` control is a popup.

The current behaviour is correct I guess.

Am I missing anything?

**Comment by niels9001** [comment]
Ah yes, you are correct. But shouldn't flyouts dismiss when other elements/dialogs get (primary) focused.

**Comment by ShankarBUS** [comment]
This is WPF Popup's default behaviour. But there is an option to close it when gone out of focus.
See [Popup.StaysOpen](https://docs.microsoft.com/en-us/dotnet/api/system.windows.controls.primitives.popup.staysopen).

@Kinnara FYI.

**Comment by ShankarBUS** [comment]
You can also hide the flyout from the code while opening the ContentDialog IIRC.

**Comment by Kinnara** [comment]
With WinUI, the dialog will correctly show over the flyout, but the flyout still needs to be dismissed manually.

**Comment by ShankarBUS** [comment]
As this issue is due to misusing or misunderstanding those controls' functionalities rather than a bug in this project, could this issue be closed now?

The flyout could be manually dismissed by calling `Flyout.Hide()` method.
