### ISSUE TITLE
ContentDialog is not centered when MaxWidth/MaxHeight not set?

### ISSUE THREAD

**Issue by niels9001** [Kinnara/ModernWpf#222]
ContentDialog is not always centered. It requires the window to resize before it's vertically/horizontall centered again. It seems that setting the MaxWidth / MaxHeight solves the issue.

Window XAML:

![image](https://user-images.githubusercontent.com/9866362/101282598-66abdb80-37d6-11eb-92eb-fce122fcf254.png)

Behavior:
![Dialogrenderingissue](https://user-images.githubusercontent.com/9866362/101282647-98bd3d80-37d6-11eb-99f3-19dc42aa211a.gif)

**Comment by Kinnara** [comment]
Thanks for reporting.

**Comment by niels9001** [comment]
@Kinnara Thanks for fixing 😁! When will this be part of the NuGet package?
