### ISSUE TITLE
TextBox context menu is not properly styled

### ISSUE THREAD

**Issue by niels9001** [Kinnara/ModernWpf#223]
Running into an issue where if a TextBox is set to ReadOnly, the context menu that comes with the control by default is not styled properly (see topic https://github.com/microsoft/PowerToys/issues/8332):

Actual result:
![image](https://user-images.githubusercontent.com/9866362/101282764-3284ea80-37d7-11eb-81cc-a92580bb67ac.png)

Expected result (in terms of styling):
![image](https://user-images.githubusercontent.com/9866362/101282774-43356080-37d7-11eb-9a0f-0ebe69664425.png)

**Comment by ShankarBUS** [comment]
Could you guide me to the xaml of the textbox? I can't seem to find it on the PowerToys repo 😅.

**Comment by ShankarBUS** [comment]
Got it!

https://github.com/microsoft/PowerToys/blob/375953641bfd63686ed456a8453852d79e9288f5/src/modules/colorPicker/ColorPickerUI/Controls/ColorFormatControl.xaml#L31

Looks like you are using a custom style and not the one provided within this library. Thus, the default context menu from WPF is being used.

See if this helps,

https://github.com/Kinnara/ModernWpf/blob/92ecdb90ee1d56197abde4a593c1050bd78060d7/ModernWpf/Styles/TextBox.xaml#L33-L34

**Comment by ShankarBUS** [comment]
@niels9001, did it work?

**Comment by niels9001** [comment]
@ShankarBUS Ah yes, you are right - incorrect style was referenced.
