### ISSUE TITLE
ContentDialog background offset

### ISSUE THREAD

**Issue by niels9001** [Kinnara/ModernWpf#227]
![image](https://user-images.githubusercontent.com/9866362/101407026-8debd100-38da-11eb-9430-3ddb2691de33.png)

The backdrop is not covering the complete window.

TItlebar is set to modernstyle.

**Comment by Kinnara** [comment]
Can't seem to reproduce with the latest commit in the editor-fluent branch. Looks like it's already solved?

**Comment by niels9001** [comment]
Yeah, seems like it! I'll re-open this issue if it re-occurs.
