### ISSUE TITLE
Add Accessibility for ToggleSwitch 

### ISSUE THREAD

**Issue by bjit311** [Kinnara/ModernWpf#228]
The toggleswitch control can't set control's name, added AutomationProperties.Name doesn't work, the switch is "" as thumb, please review inspect's result below.  
https://docs.microsoft.com/en-us/windows/win32/winauto/inspect-objects
![thumb](https://user-images.githubusercontent.com/75471402/101598243-d4544380-3a32-11eb-8239-a97b27847907.PNG)

**Comment by Kinnara** [comment]
Good point. I'll try to add some support for accessibility. Ideally it would match the accessibility experience of the UWP counterpart.
