### ISSUE TITLE
Close/Maximize/Minimize button's name is lost in window if added ui:WindowHelper.UseModernWindowStyle="True"

### ISSUE THREAD

**Issue by bjit311** [Kinnara/ModernWpf#229]
The Close/Maximize/Minimize buttons control's name become  if added ui:WindowHelper.UseModernWindowStyle="True" in window

without  ui:WindowHelper.UseModernWindowStyle="True" 
![before](https://user-images.githubusercontent.com/75471402/101632300-ac7bd480-3a60-11eb-8889-63720054dac1.PNG)

with ui:WindowHelper.UseModernWindowStyle="True" 
![after](https://user-images.githubusercontent.com/75471402/101632312-b00f5b80-3a60-11eb-9832-4ef49f9a84e9.PNG)
Minimize -->M20,8l20...
Maximize-->M20,0L20...
Close-->M11,...

**Comment by ShankarBUS** [comment]
That's not the name,

That the path data of the content within the buttons.

Accessibility is indeed an important scope of software development.

@bjit311, what tool are you using to find the accessibility of the application? Do you know how to fix it?

**Comment by Kinnara** [comment]
Thanks for reporting.
