### ISSUE TITLE
AppBarToggleButton is not greyed out when set to disabled.

### ISSUE THREAD

**Issue by bjit311** [Kinnara/ModernWpf#237]
Steps:
1.Create a AppBarToggleButton.
2.Set the IsEnabled="False".
3.The AppBarToggleButton is Not greyed out

Code:
            <ui:AppBarToggleButton Label="AutoLogin1"
                                   IsEnabled="False" />
            <ui:AppBarToggleButton Label="AutoLogin2"
                                   IsEnabled="True" />

Screenshots:
1. No mouse hover
![nomousehover](https://user-images.githubusercontent.com/75471402/102319984-a7fe7100-3fb6-11eb-8afe-6a0c899e856f.png)
2. Mouse hover AutoLogin1
![autotlogin1](https://user-images.githubusercontent.com/75471402/102320028-b9e01400-3fb6-11eb-9243-3ba83ce7232b.png)
3. Mouse hover AutoLogin2
![autotlogin2](https://user-images.githubusercontent.com/75471402/102320080-cc5a4d80-3fb6-11eb-904e-757438181f59.png)

Note:
There was a similar issue in another control in microsoft-ui-xaml https://github.com/microsoft/microsoft-ui-xaml/issues/56 for your reference.

**Comment by Kinnara** [comment]
Thanks for reporting.
