### ISSUE TITLE
DesignTimeResources !!

### ISSUE THREAD

**Issue by oSethoum** [Kinnara/ModernWpf#239]
Am really struggling here, as a beginner in WPF, where is the documentation for using this UI, for example i can't seem to find a way to use TabControlPivotStyle 

Please try to document it.

**Comment by lgztx96** [comment]
see [Enable IntelliSense for XAML resources](https://github.com/Kinnara/ModernWpf/wiki/Common-Tasks#enable-intellisense-for-xaml-resources)
![Snipaste_2020-12-17_08-57-03](https://user-images.githubusercontent.com/29275743/102424491-3110b900-4046-11eb-800d-f3f21a58431b.png)

**Comment by oSethoum** [comment]
Thank you very much ❤

**Comment by oSethoum** [comment]
I followed the instructions, but still I can't get IntelliSense 
I got this.
![image](https://user-images.githubusercontent.com/46224889/102675489-dd16e900-4199-11eb-8482-7017a8b378ea.png)

![image](https://user-images.githubusercontent.com/46224889/102675524-0a639700-419a-11eb-99b7-5f43ab21fe56.png)
