### ISSUE TITLE
In darkmode you can hardly see the dialog borders

### ISSUE THREAD

**Issue by Symbai** [Kinnara/ModernWpf#253]
The dark mode should enlighten the background when a dialog is shown. Because since its black already, the dialog also has a black background you can hardly see the dialog window which looks extremely odd in many cases. Either this or changing the border colors in dark theme to something else.

Light:
![image](https://user-images.githubusercontent.com/14368203/104309951-3b9e6100-54d3-11eb-8943-b7a264456049.png)

Dark:
![image](https://user-images.githubusercontent.com/14368203/104309969-422cd880-54d3-11eb-9cf3-27ccf63be42a.png)

**Comment by luojunyuan** [comment]
the win10 setting is same as this
![image](https://user-images.githubusercontent.com/28323948/104547725-31629b00-566a-11eb-8aee-95362c0ed550.png)
