### ISSUE TITLE
How to close a dialog in code?

### ISSUE THREAD

**Issue by Symbai** [Kinnara/ModernWpf#254]
I want to show the "Cancel" button centered but using the inbuilt close button feature of ModernWPF makes the button aligned to the right without a way to change it.

So I've instead created my own cancel button but how to I close the dialog in code?  There is no `Close()` method and the `CloseButtonCommand` is `NULL` if the inbuilt close button isn't used.

**Comment by TheXamlGuy** [comment]
Call `Hide()` method to close the ContentDialog.

**Comment by Symbai** [comment]
Does the dialog gets disposed? Because I create it in code like this:

```
var dlg = new MyDialog();
await dlg.ShowAsync();
```

when it just gets hidden wouldn't it leak memory?

**Comment by TheXamlGuy** [comment]
Yes, the ContentDialog will be removed from the tree and disposed of. The same Hide() method is also called by the Primary, Secondary, and Cancel buttons as seen [on this line].(https://github.com/Kinnara/ModernWpf/blob/826426c4f6494080b4de30c24250bb0102b09b1e/ModernWpf.Controls/ContentDialog/ContentDialog.cs#L738).
