### ISSUE TITLE
Scrollbar not right-aligned properly inside TextBox

### ISSUE THREAD

**Issue by rgwood** [Kinnara/ModernWpf#256]
Hi, thanks for making ModernWPF! It's awesome.

I've run into a minor issue when using ModernWPF 0.9.3 on .NET 5 and Core 3.1; in a multi-line TextBox, the vertical scroll bar is aligned with the right of the text content, not the right of the TextBox:

![image](https://user-images.githubusercontent.com/26268125/104394241-11609980-54fb-11eb-9f0a-5128b95034a5.png)

Here's what it should look like (using the default WPF styling):

![image](https://user-images.githubusercontent.com/26268125/104394517-a2d00b80-54fb-11eb-9f5f-8906045ef105.png)

I've created a simple reproduction [here](https://github.com/rgwood/ModernWpfScrollbarRepro); the offending TextBox [is in MainWindow.xaml](https://github.com/rgwood/ModernWpfScrollbarRepro/blob/master/ModernWpfRepro/MainWindow.xaml#L16-L22):

```
        <TextBox
            x:Name="TextBoxWithBadScrollbar"
            Height="100"
            Margin="10"
            HorizontalAlignment="Stretch"
            AcceptsReturn="True"
            VerticalScrollBarVisibility="Visible" />
```

**Comment by Kinnara** [comment]
Thanks for the detailed report. This should now be fixed by b3180806a56bd91f2b52f17ad92b87499c11b3d5.
