### ISSUE TITLE
AutoSuggestBox Empty Space

### ISSUE THREAD

**Issue by ghost1372** [Kinnara/ModernWpf#273]
How can I remove this gap?
![xa](https://user-images.githubusercontent.com/9213496/106363853-56306100-6340-11eb-8bb9-d2ba36df54fa.png)

The demo version has no problem
![xc](https://user-images.githubusercontent.com/9213496/106363868-66484080-6340-11eb-9a26-3ac83234036e.png)

**Comment by FreddyD-GH** [comment]
I can confirm that there is no gap when using the default style.  From the picture that you posted, it looks like the first item is null, or maybe just has a null/empty title.  Have you ensured that your first suggestion item is a valid object?

**Comment by ghost1372** [comment]
@FreddyD-GH 
This is my code

```
var suggestions = new List<string>();
 var history = GlobalData.Config.History; 
if (args.Reason == AutoSuggestionBoxTextChangeReason.UserInput) {
 var querySplit = sender.Text.Split(' ');
 var matchingItems = history.Where( item => { bool flag = true; foreach (string queryToken in querySplit) {
 if (item.IndexOf(queryToken, StringComparison.CurrentCultureIgnoreCase) < 0) { flag = false; } } return flag; }); 

foreach (var item in matchingItems) { suggestions.Add(item); } 
if (suggestions.Count > 0) { 
for (int i = 0; i < suggestions.Count; i++) { autoBox.ItemsSource = suggestions; } 
} else 
{ autoBox.ItemsSource = new string[] { Lang.NoResult }; } }
```

**Comment by FreddyD-GH** [comment]
I assume that `GlobalData.Config.History` is an `IEnumerable<string>`? If so, it looks there is probably an empty string stored in there.  You could simply filter out empty entries with something like the following:
```csharp
var suggestions = new List<string>();
var history = GlobalData.Config.History; 
if (args.Reason == AutoSuggestionBoxTextChangeReason.UserInput)
{
    var querySplit = sender.Text.Split(' ');
    var matchingItems = history.Where( item => 
    {
        // CHECK FOR EMPTY STRINGS
        if (string.IsNullOrEmpty(item))
        {
            return false;
        }

        bool flag = true; foreach (string queryToken in querySplit) {
            if (item.IndexOf(queryToken, StringComparison.CurrentCultureIgnoreCase) < 0) { flag = false; }
        }
        return flag;
    }); 

foreach (var item in matchingItems) { suggestions.Add(item); } 
if (suggestions.Count > 0) { 
    // You also don't need a loop here when using ItemsSource
    //for (int i = 0; i < suggestions.Count; i++) { autoBox.ItemsSource = suggestions; } 
    autoBox.ItemsSource = suggestions;
}
else 
{ 
    autoBox.ItemsSource = new string[] { Lang.NoResult }; }
}
```

**Comment by ghost1372** [comment]
thank you @FreddyD-GH but didnt work and I checked there is no empty or null value
I think this issue should be resolved by overriding the style I just do not know which key

**Comment by FreddyD-GH** [comment]
That is strange.  I used your exact code and there is no gap for me, unless one of the suggestions is empty.  You can check the default control template at: https://github.com/Kinnara/ModernWpf/blob/master/ModernWpf.Controls/AutoSuggestBox/AutoSuggestBox.xaml

Would it be possible that you are overriding the default ListView style to put a top padding?

**Comment by ghost1372** [comment]
> That is strange. I used your exact code and there is no gap for me, unless one of the suggestions is empty. You can check the default control template at: https://github.com/Kinnara/ModernWpf/blob/master/ModernWpf.Controls/AutoSuggestBox/AutoSuggestBox.xaml
> 
> Would it be possible that you are overriding the default ListView style to put a top padding?

Of course I use another library for styles😅

**Comment by ghost1372** [comment]
thank you @FreddyD-GH  i fixed issue with this code

```
<controls:AutoSuggestBox.Resources>
    <Style TargetType="ListView" BasedOn="{StaticResource DefaultListViewStyle}"/>
</controls:AutoSuggestBox.Resources>
```
