### ISSUE TITLE
TextBox cursor issue in 0.9.3

### ISSUE THREAD

**Issue by JVimes** [Kinnara/ModernWpf#276]
For multi-line TextBoxes, the area that invokes the text cursor changed in 0.9.3. This makes it harder to place the text cursor and select text.

This issue was caused by c225dd61, which set the horizontal/vertical content alignment to `Left`/`Top`. I think they should both be `Stretch`.

![image](https://user-images.githubusercontent.com/6148201/106673877-93c70100-656f-11eb-82f0-cd1fccf7c486.png)

```xml
<TextBox TextWrapping="Wrap" AcceptsReturn="True"
         Text="Foo&#x0a;Bar" Height="100" Width="200"/>
```

**Comment by Kinnara** [comment]
Thanks for the detailed report. Should be fixed now,
