### ISSUE TITLE
ListBox Scrollbar hidden but not Collapsed. 

### ISSUE THREAD

**Issue by oSethoum** [Kinnara/ModernWpf#282]
I found out that even when there is no scrollbar in the **ListBox**, its place is still there making an area that can't be pressed 
![image](https://user-images.githubusercontent.com/46224889/108124455-851c3600-70a7-11eb-9287-bba0aca9b930.png)

**Comment by Kinnara** [comment]
Thanks for reporting. This should be fixed now.

**Comment by oSethoum** [comment]
@Kinnara  Thank You !
