### ISSUE TITLE
Cursor doesn't focus at the end of text in TextBox after click blank area

### ISSUE THREAD

**Issue by bjit311** [Kinnara/ModernWpf#299]
Steps:
1. Input some text in textbox
2. make the cursor in the text and then make the cursor out of the textbox
3. click the blank area in the textbox
Result: Cursor doesn't focus at the end of text 

Note:
Investigating the TextBox control by snoop/VisualTree, the BorderElement's HorizonAlignment property value is stretch, but the PART_ContentHost's HorizonAlignment property value is left. The issue will not be reproduced if I modified the PART_ContentHost's HorizonAlignment property value to stretch.

![texbox](https://user-images.githubusercontent.com/75471402/109244405-9f79b080-7819-11eb-9321-8dbcb5e1933a.png)
![contentarea](https://user-images.githubusercontent.com/75471402/109244417-a3a5ce00-7819-11eb-8410-0704d9ce0f5c.png)

**Comment by ndrnesterov** [comment]
Right! Please fix this ...

**Comment by Kinnara** [comment]
Thanks for the detailed report. This should now be fixed by b3180806a56bd91f2b52f17ad92b87499c11b3d5.
