### ISSUE TITLE
A control for textbox numbers?

### ISSUE THREAD

**Issue by Coke21** [Kinnara/ModernWpf#3]
Hi, I have been using it for a few days and I really like your library. I looked through the SampleApp and didn't see any controls for textbox numbers. Something like https://mahapps.com/controls/numericupdown.html in Mahapps.Metro. Are there any plans for adding such control? Thank you for your answer.

**Comment by Kinnara** [comment]
Once the WinUI `NumberBox` is mature enough I can probably port it over. In the meantime, you can just use the controls in MahApps.Metro or other libraries. I put together [a basic style](https://github.com/Kinnara/ModernWpf/blob/master/MahAppsInteropSample/App.xaml) for the MahApps `NumericUpDown` which can serve as a starting point.

![image](https://user-images.githubusercontent.com/1617766/68646084-0c016b00-0555-11ea-80f7-00f8a80ac0cf.png)

**Comment by Coke21** [comment]
Thank you so much for your help. Everything works now. Just a small note, you might want to add:
`ui:ControlHelper.Header="{TemplateBinding ui:ControlHelper.Header}"` in the TextBox in App.xaml so you can actually use the Header property. Thank you again.

**Comment by Kinnara** [comment]
Update: [NumberBox](https://github.com/Kinnara/ModernWpf/wiki/NumberBox) has been ported from WinUI.
