### ISSUE TITLE
FlyoutService requires Button, but ButtonBase is sufficient

### ISSUE THREAD

**Issue by andrew-boyarshin** [Kinnara/ModernWpf#30]
Because of the unnecessary limitation, `Flyout` can't be attached to `HyperlinkButton`, which I expected to work OOB.

P.S. Thanks for your project, it really is the best WPF theme & control library out there!

**Comment by Kinnara** [comment]
Thank you. The limitation is carried over from [UWP](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.button.flyout), which this library attempts to align with API/behavior wise. As a workaround, you can use the `FlyoutBase.AttachedFlyout` attached property to associate a Flyout with the HyperlinkButton and call `FlyoutBase.ShowAttachedFlyout` method to display the flyout.

**Comment by andrew-boyarshin** [comment]
@Kinnara oh, so that's UWP issue (which will obviously never get fixed, since that would break compat). Thanks for the workaround, you can close this issue if the goal of the project is to recreate UWP API 1:1.
