### ISSUE TITLE
No Header attribute in ComboBox

### ISSUE THREAD

**Issue by Eliasyoussef47** [Kinnara/ModernWpf#302]
I can't use the Header attribute with `<ComboBox>` to get a text above the ComboBox like in `<ui:ToggleSwitch Header="Activated"/>` 

![ComboBox](https://user-images.githubusercontent.com/31613492/109957311-0c42ee00-7ce5-11eb-93b2-924bb773655b.png)

**Comment by ghost1372** [comment]
@Eliasyoussef47 
use controlhelper attachedProperty

**Comment by Eliasyoussef47** [comment]
@ghost1372 Could you please show me an example?

**Comment by Eliasyoussef47** [comment]
Ok I found the solution.
`<ComboBox ui:ControlHelper.Header="Method">`
