### ISSUE TITLE
OverridesDefaultStyle interferes with BasedOn in custom controls?

### ISSUE THREAD

**Issue by JVimes** [Kinnara/ModernWpf#306]
I subclassed `Window` to create my `Dialog` class. It's a custom control, so its default style is in Generic.xaml. I set BasedOn to [DefaultWindowStyle](https://github.com/Kinnara/ModernWpf/blob/a23d5bcc6e8c857161f7c7dfe6b3d18d548259fe/ModernWpf/Styles/Window.xaml):

```xml
<ResourceDictionary.MergedDictionaries>
    <ResourceDictionary Source="/ModernWpf;component/Styles/Window.xaml" />
</ResourceDictionary.MergedDictionaries>

<Style TargetType="{x:Type local:Dialog}" BasedOn="{StaticResource DefaultWindowStyle}">
    <!-- Setters specific to Dialog class -->
</Style>
```
But since DefaultWindowStyle sets OverridesDefaultStyle, I get an exception:

> InvalidOperationException: 'Cannot set OverridesDefaultStyle property in the default Style.'

I tried setting OverridesDefaultStyle to false in my Dialog style, but got the same error.

A lot of ModernWpf styles set OverridesDefaultStyle. Does this mean they can't be used as the basis for custom control styles? Is there a solution or workaround? Thank you.

**Comment by Kinnara** [comment]
Thanks for reporting. I've added a `BaseWindowStyle` to enable this scenario.
