### ISSUE TITLE
GridView Accessibility Border not showing on the edges 

### ISSUE THREAD

**Issue by oSethoum** [Kinnara/ModernWpf#309]
Hello, 
I would like to report this ( am not sure if it is an issue ), you can see in the edge ( demonstrated by the red color ) there is no black border. 

![image](https://user-images.githubusercontent.com/46224889/110906989-0cf30a00-830d-11eb-8ae1-7f69ab918ad3.png)

**Comment by Kinnara** [comment]
Good catch. The left and top borders are clipped by the parent `ScrollViewer`. A workaround is to set `Margin` on the `GridViewItem`s or `Padding` on the `GridView`.
