### ISSUE TITLE
ThemeShadowChrome need optimize

### ISSUE THREAD

**Issue by wuyang26** [Kinnara/ModernWpf#31]
the popup shadow is cool,but it is not better then the microsoft xaml control,
the bottom shadow'color is too deep,and the left/right effect too weak
I modify: effect.ShadowDepth = 0.2 * depth;
                effect.BlurRadius = 0.8 * depth + c_shadowMargin;
we hope look the xaml control's shadow effect.

**Comment by Kinnara** [comment]
Agreed. Will look into this.
