### ISSUE TITLE
DataGrid sizing issue

### ISSUE THREAD

**Issue by DarkbladeEU** [Kinnara/ModernWpf#321]
I don't know if I'm configuring it wrong or something but this is so frustrating. 

![image](https://user-images.githubusercontent.com/68714839/113203304-cdf90a00-9263-11eb-87b9-52c92eb9604e.png)

The following image shows that the header "container", or whatever it is, is longer than the items inside the DataGrid itself. I've tried several ways to try make this go away however to no avail. I've tried changing the width of the DataGrid, enabling `AutoGenerateColumns`, changing the width of columns, not including any columns whatsoever, and nothing seems to work.

DataGrid in XAML:
![image](https://user-images.githubusercontent.com/68714839/113203642-32b46480-9264-11eb-8f11-b60e065cc4b0.png)

**Comment by oSethoum** [comment]
I believe that's for the scrollbar which is a normal behavior.

**Comment by DarkbladeEU** [comment]
Hi,

Even if this feature is intentional, surely it should be invisible until necessary?

It's incredibly off-putting seeing a line that essentially exists for no reason
