### ISSUE TITLE
How to install the ModernWpf UI to a WPF .Net Framework using VB

### ISSUE THREAD

**Issue by shannonfonseka** [Kinnara/ModernWpf#333]

**Comment by ghost1372** [comment]
I have not tried WPF with VB, but xaml codes are no different. Just install the nuget package and set resources
```
<Application
    ...
    xmlns:ui="http://schemas.modernwpf.com/2019">
    <Application.Resources>
        <ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>
                <ui:ThemeResources />
                <ui:XamlControlsResources />
            </ResourceDictionary.MergedDictionaries>
        </ResourceDictionary>
    </Application.Resources>
</Application>
```

**Comment by redkross** [comment]
Thank you for your reply. It's ok for the XAML / Nuget package, indeed this part is similar, but I'm struggling with the navigation system between the MainWindow and child pages. I don't know how to implement this part. I would just like to build a very simple application with 2 or 3 pages (UserControl?).

**Comment by ghost1372** [comment]
@redkross Use these codes

```
<ui:NavigationView SelectionChanged="NavigationView_SelectionChanged" PaneDisplayMode="Left">
        <ui:NavigationView.MenuItems>
            <ui:NavigationViewItem Content="About" Tag="about"/>
            <ui:NavigationViewItem Content="Main" Tag="main"/>
        </ui:NavigationView.MenuItems>

        <ui:Frame Name="frm"/>
    </ui:NavigationView>
```

Create 2 UserControl named **AboutPage** and **MainPage**
```
Private Sub NavigationView_SelectionChanged(sender As ModernWpf.Controls.NavigationView, args As ModernWpf.Controls.NavigationViewSelectionChangedEventArgs)
        Dim selectedItem = CType(args.SelectedItem, NavigationViewItem)
        If selectedItem IsNot Nothing Then
            Dim tag = selectedItem.Tag.ToString()

            Select Case selectedItem.Tag
                Case "about"
                    frm?.Navigate(GetType(AboutPage))
                Case "main"
                    frm?.Navigate(GetType(MainPage))
            End Select
        End If
    End Sub
```
Result

![3](https://user-images.githubusercontent.com/9213496/116739258-b484e280-aa08-11eb-8d59-f7d32dfbb5f6.gif)

**Comment by redkross** [comment]
@ghost1372 Thanks for your fast reply. I'll try this asap.

**Comment by redkross** [comment]
Ok, this is a good starting point for me, many thanks ! 👍 
Hope this could help @shannonfonseka  as well.

Bye

**Comment by shannonfonseka** [comment]
> I have not tried WPF with VB, but xaml codes are no different. Just install the nuget package and set resources
> 
> ```
> <Application
>     ...
>     xmlns:ui="http://schemas.modernwpf.com/2019">
>     <Application.Resources>
>         <ResourceDictionary>
>             <ResourceDictionary.MergedDictionaries>
>                 <ui:ThemeResources />
>                 <ui:XamlControlsResources />
>             </ResourceDictionary.MergedDictionaries>
>         </ResourceDictionary>
>     </Application.Resources>
> </Application>
> ```
I have tried @ghost1372 reply 👆🏻, that works 👌🏻.
```xaml
<Application x:Class="Application"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="clr-namespace:WpfApp2" xmlns:ui="http://schemas.modernwpf.com/2019"
             StartupUri="MainWindow.xaml">
    <Application.Resources>
        <ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>
                <ui:ThemeResources />
                <ui:XamlControlsResources />
                <!-- Other merged dictionaries here -->
            </ResourceDictionary.MergedDictionaries>
            <!-- Other app resources here -->
        </ResourceDictionary>
    </Application.Resources>
</Application>
```
I copied and added it to the Application.xaml (I hope I did it correctly), but I get an error called:
![image](https://user-images.githubusercontent.com/58655133/118287711-5a4c4d00-b4f1-11eb-95ef-3e573962b881.png)

I have been working on Windows Form App (in the.NET Framework) but not on WPF Apps so I don't know much about it 😕.

**Comment by shannonfonseka** [comment]
> I have not tried WPF with VB, but xaml codes are no different. Just install the nuget package and set resources
> 
> ```
> <Application
>     ...
>     xmlns:ui="http://schemas.modernwpf.com/2019">
>     <Application.Resources>
>         <ResourceDictionary>
>             <ResourceDictionary.MergedDictionaries>
>                 <ui:ThemeResources />
>                 <ui:XamlControlsResources />
>             </ResourceDictionary.MergedDictionaries>
>         </ResourceDictionary>
>     </Application.Resources>
> </Application>
> ```
I have tried @ghost1372 reply 👆🏻, that works 👌🏻. Thanks. (there was no error in the file)
```xaml
<Application x:Class="Application"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="clr-namespace:WpfApp2" xmlns:ui="http://schemas.modernwpf.com/2019"
             StartupUri="MainWindow.xaml">
    <Application.Resources>
        <ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>
                <ui:ThemeResources />
                <ui:XamlControlsResources />
                <!-- Other merged dictionaries here -->
            </ResourceDictionary.MergedDictionaries>
            <!-- Other app resources here -->
        </ResourceDictionary>
    </Application.Resources>
</Application>
```
I copied the code and pasted to the Application.xaml (I hope I did it correctly).
But I get an error like this when I press the run button:
 ![image](https://user-images.githubusercontent.com/58655133/118289602-270abd80-b4f3-11eb-8eeb-64e53e5c6f75.png) 

I have been working on Windows Form App (in the.NET Framework) but not on WPF Apps so I don't know much about it 😕.

**Comment by ghost1372** [comment]
@shannonfonseka  try this:
Solution Explorer -> right-click References -> "Migrate packages.config to PackageReference"
or
right-click packages.config -> "Migrate packages.config to PackageReference"

**Comment by shannonfonseka** [comment]
> @shannonfonseka try this:
> Solution Explorer -> right-click References -> "Migrate packages.config to PackageReference"
> or
> right-click packages.config -> "Migrate packages.config to PackageReference"

Oh great! thanks @ghost1372 👌🏻 it worked🥳🙌🏻🥂. This should be added to the repository's documentation, if someone needs help in installing this to WPF apps in VB language
