### ISSUE TITLE
CommandBar: If nothing listed in SecondaryCommands, overflow items don't show up

### ISSUE THREAD

**Issue by Deadpikle** [Kinnara/ModernWpf#36]
Hey,

If there is a command bar with nothing listed in `ui:CommandBar.SecondaryCommands`, when the window/control width is decreased, the overflow button shows up, but clicking the button doesn't do anything. If there is initially a secondary command, overflow works as expected.

The easiest way to replicate it is to remove the secondary command from the demo's `CommandBarPage` sample, then make the sample window very narrow so that the `...` button appears. Once you click the button, no popup appears.

XAML:
```
<ui:CommandBar x:Name="PrimaryCommandBar">
    <ui:AppBarButton x:Name="addButton" Icon="Add" Label="Add" Click="OnElementClicked" />
    <ui:AppBarButton x:Name="editButton" Icon="Edit" Label="Edit" Click="OnElementClicked" />
    <ui:AppBarButton x:Name="shareButton" Icon="Share" Label="Share" Click="OnElementClicked" />
    <ui:CommandBar.SecondaryCommands>
    </ui:CommandBar.SecondaryCommands>
</ui:CommandBar>
```

Thanks!

**Comment by Kinnara** [comment]
Good catch, I'll look into it. Thanks for reporting!
