### ISSUE TITLE
Please support .net 5

### ISSUE THREAD

**Issue by LuGuangguang** [Kinnara/ModernWpf#367]
I know there are many issues had mentioned it,like  #187 . 
But I can't undersander how can I  change  '.net 5' to targeting 'net5.0-windows10.0.18362.0'. 
I think #208 said is me.
![图片](https://user-images.githubusercontent.com/34500722/123599130-db546f00-d827-11eb-8656-5ea06fa8cb12.png)

**Comment by ghost1372** [comment]
.net 5 already supported. you should edit csproj file

**Comment by LuGuangguang** [comment]
> 
> 
> .net 5 already supported. you should edit csproj file

I had solved this problem.I changed the "<TargetFramework>net5.0-windows</TargetFramework>" To 
"<TargetFramework>net5.0-windows10.0.18362.0</TargetFramework>",but it running won't auto save,
so it  throw an exception.So it need to save.
Thank you.
