### ISSUE TITLE
Change of Windows scaling requires a restart

### ISSUE THREAD

**Issue by Alex4SSB** [Kinnara/ModernWpf#372]
Until then, apps with ModernWPF are blurry, unlike other WPF apps.

**Comment by ShankarBUS** [comment]
I guess you didn't enable DPI awareness for your application.

You have to make changes to the app.manifest or call some methods to do that.

There are official docs on how to do that. Try searching them.

ModernWpf doesn't have anything to do with this.

**Comment by Alex4SSB** [comment]
Ok, thanks, that did solve the problem.
