### ISSUE TITLE
ComboBox - Popup issue

### ISSUE THREAD

**Issue by ShankarBUS** [Kinnara/ModernWpf#38]
ComboBox when expanded above a certain width, the popup breaks. I cant find which is causing this problem. This must be a bug in ThemeShadowChrome

![Untitled](https://user-images.githubusercontent.com/54765038/75027570-c85bbd00-54c4-11ea-8040-2390ab237660.jpg)
![Untitled1](https://user-images.githubusercontent.com/54765038/75027576-cabe1700-54c4-11ea-882f-106b9d31d366.jpg)
![Untitled2](https://user-images.githubusercontent.com/54765038/75027578-cb56ad80-54c4-11ea-81e2-367288be7905.jpg)
![Untitled3](https://user-images.githubusercontent.com/54765038/75027580-cbef4400-54c4-11ea-81e9-281cfd9d8280.jpg)

**Comment by Kinnara** [comment]
Thanks for reporting. I'll look into it.
