### ISSUE TITLE
Suggestion: Make a scrolling animation when using the mouse wheel

### ISSUE THREAD

**Issue by shannonfonseka** [Kinnara/ModernWpf#419]
For example, in the Settings app and when scrolling up or down, it has a smooth gliding effect. Is that possible to make it in the ScrollViewer component?

**Comment by luojunyuan** [comment]
Check the ModernFlyouts' [ScrollViewerEx](https://github.com/ModernFlyouts-Community/ModernFlyouts/blob/2894b2d9f3ecf237de2a8828b2d5ded905aec12d/ModernFlyouts/Controls/ScrollViewerEx.cs)

**Comment by shannonfonseka** [comment]
> Check the ModernFlyouts' [ScrollViewerEx](https://github.com/ModernFlyouts-Community/ModernFlyouts/blob/2894b2d9f3ecf237de2a8828b2d5ded905aec12d/ModernFlyouts/Controls/ScrollViewerEx.cs)

absolutely purrfect 😻

Question, how can I add it to my project and it's in C# I'm working on VB 😳?

**Comment by luojunyuan** [comment]
I don't know VB, may be you can rewrite that with VB. The core helper file [ScrollViewerHelperEx](https://github.com/ModernFlyouts-Community/ModernFlyouts/blob/2894b2d9f3ecf237de2a8828b2d5ded905aec12d/ModernFlyouts/Helpers/ScrollViewerHelperEx.cs) about 150 lines. You only need these two files to work with xaml.
