### ISSUE TITLE
Build Error .NET 5

### ISSUE THREAD

**Issue by LiMa-lab** [Kinnara/ModernWpf#425]
I get the following Error Message with 0.9.4
Severity	Code	Description	Project	File	Line	Suppression State
Error	NETSDK1149	ModernWpf.dll cannot be referenced because it uses built-in support for WinRT, which is no longer supported in .NET 5 and higher.  An updated version of the component supporting .NET 5 is needed. For more information, see https://aka.ms/netsdk1149	DatenbankVerwaltung	C:\Program Files\dotnet\sdk\5.0.404\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets	914	

Anyone else having this problem?

**Comment by MostlyWhat** [comment]
Someone should close this
