### ISSUE TITLE
Can provide the executable of ModernWpf SampleApp

### ISSUE THREAD

**Issue by moob158** [Kinnara/ModernWpf#428]
Please, can you provide the executable of ModernWpf SampleApp?

I can't compile, gives me too many errors.

thanks and sorry for post this here.

**Comment by alxkalinin** [comment]
You can take binaries [from my own fork](https://github.com/alxkalinin/ModernWpf/releases/tag/v0.9.4).

**Comment by moob158** [comment]
> You can take binaries [from my own fork](https://github.com/alxkalinin/ModernWpf/releases/tag/v0.9.4).

Thank you very much :)
