### ISSUE TITLE
Rendering issues with UseModernWindowStyle

### ISSUE THREAD

**Issue by milos12345** [Kinnara/ModernWpf#43]
When Window has this
`ui:WindowHelper.UseModernWindowStyle="True`
it causes a weird rendering bluring-glitch in listbox when the content changes. See here:

![issueWPF](https://user-images.githubusercontent.com/5231547/75925962-9d178d00-5e37-11ea-80b9-41021387ae48.gif)

Setting `UseLayoutRounding="True"` on the ListBox or the window fixes it. Maybe that should be mentioned in documentation somewhere if it can't be fixed without setting the `UseLayoutRounding`

Edit: Seems to be only when it defaults back to software rendering

**Comment by Kinnara** [comment]
We should probably use layout rounding by default. I've seen some other rather common issues that can be fixed by setting `UseLayoutRounding="True"`.

**Comment by Kinnara** [comment]
Fixed by a54ae79b04435a109df5489590df5022cc7825dc.
