### ISSUE TITLE
Avalonia Port

### ISSUE THREAD

**Issue by furesoft** [Kinnara/ModernWpf#44]
could you port this to AvaloniaUI?

**Comment by Kinnara** [comment]
Might happen in the future, but there are no plans at the moment.

**Comment by rstm-sf** [comment]
At least one item currently exists https://github.com/Deadpikle/AvaloniaProgressRing

**Comment by maxkatz6** [comment]
And another one https://github.com/amwx/FluentAvalonia/tree/master/FluentAvalonia

**Comment by AlonAm** [comment]
When using Avalonia, on mac or linux, does it make sense to use a WinUI like user interface?

**Comment by rstm-sf** [comment]
Yes, some elements look good!) https://twitter.com/AvaloniaUI/status/1272648131872776194
