### ISSUE TITLE
Size issue with SymbolIcon as Button Content

### ISSUE THREAD

**Issue by milos12345** [Kinnara/ModernWpf#45]
This is how I have been using buttons with symbols
`<Button  FontFamily="Segoe MDL2 Assets" >&#xE73E;</Button>`

So I was hoping I could do this
`<Button><ui:SymbolIcon Symbol="Accept" /></Button>`

But then the size is not right (2nd one)
![image](https://user-images.githubusercontent.com/5231547/76687548-64c43b80-65fb-11ea-850e-cd2bdac625b0.png)

If I then try to change the Width and Height or SymbolIcon I get it cropped  (2nd one)
![image](https://user-images.githubusercontent.com/5231547/76687570-8291a080-65fb-11ea-829d-9906b752e404.png)

**Comment by ShankarBUS** [comment]
It's because the FontSize of SymbolIcon is internal and others won't be able to set it. It is fixed as 20.0

**Comment by mikecoxlong** [comment]
That's because the **SymbolIcon**'s **FontSize** property is internal, user won't be able to change it. The issue here is the FontSize is fixed at 20.0 😔

**Comment by Kinnara** [comment]
UWP has the same behavior so this could be considered to be by design. One solution is wrapping the icon in a `Viewbox`:
```xaml
<Button Width="24" Height="24" Padding="4">
    <Viewbox>
        <ui:SymbolIcon Symbol="Accept" />
    </Viewbox>
</Button>
```

**Comment by ShankarBUS** [comment]
I prefer the FontIcon control to the SymbolIcon control, it has a FontSize property and it's more flexible than the latter.
