### ISSUE TITLE
ModernWPF Sample App how to get this "slow" mode effect?

### ISSUE THREAD

**Issue by Coke21** [Kinnara/ModernWpf#46]
Hi, sorry for not explaining it enough. How do I get this effect?
https://gyazo.com/8c2fc438515d8e20dbf311fc72066813
Pretty much when switching between items on the left. What is the name of this property? Also, can it be used in TabControl?

**Comment by mikecoxlong** [comment]
That's **PageTransition** in a **TransitionFrame** I guess? I don't think you can do it with **TabControl**

**Comment by Kinnara** [comment]
It's the [CrossFadeContentControl](https://github.com/Kinnara/ModernWpf/blob/master/samples/SamplesCommon/CrossFadeContentControl.cs) in the samples. It seems to work to some extent [when used as the TabControl's content host](https://gist.github.com/Kinnara/b8a1b7e5bd5d268c029c9c5aac0718a7) but note that `TabControl` does require a `ContentPresenter` and not providing one may result in loss of certain functions. For example, the `TabItemAutomationPeer` likely won't work correctly.

**Comment by Coke21** [comment]
Thanks for the replies, what is the `sc` namespace, in` sc:CrossFadeContentControl`?

**Comment by YuqseLx** [comment]
It's SamplesCommon
