### ISSUE TITLE
Can set overlay brush of ContentDialog

### ISSUE THREAD

**Issue by s77zz** [Kinnara/ModernWpf#49]
make dialog more concernable as in mahapps.metro.simplechildwindow

![image](https://user-images.githubusercontent.com/20233712/77816211-de7c1f00-70fb-11ea-9eb5-3b2884639203.png)

**Comment by Kinnara** [comment]
One way to achieve this is by overriding the `SystemControlPageBackgroundMediumAltMediumBrush` resource. It's not really exclusive to ContentDialog but isn't currently used elsewhere, so should be okay to override. For example:
```xaml
<ui:ThemeResources>
    <ui:ThemeResources.ThemeDictionaries>
        <ResourceDictionary x:Key="Light">
            <ResourceDictionary.MergedDictionaries>
                <ui:DefaultThemeResources Key="Light" />
            </ResourceDictionary.MergedDictionaries>
            <StaticResource x:Key="SystemControlPageBackgroundMediumAltMediumBrush" ResourceKey="SystemControlBackgroundBaseMediumBrush" />
        </ResourceDictionary>
    </ui:ThemeResources.ThemeDictionaries>
</ui:ThemeResources>
```

**Comment by s77zz** [comment]
> ```
> SystemControlBackgroundBaseMediumBrush
> ```

Thank you K, I achive by additional step, otherways report error, source not found

`
<ui:ThemeResources>
                    <ui:ThemeResources.ThemeDictionaries>
                        <ResourceDictionary x:Key="Light">
                            <ResourceDictionary.MergedDictionaries>
                                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Themes/Light.Blue.xaml"/>
                                <ResourceDictionary Source="pack://application:,,,/ModernWpf;component/ThemeResources/Light.xaml"/>
                            </ResourceDictionary.MergedDictionaries>
                            <StaticResource x:Key="SystemControlPageBackgroundMediumAltMediumBrush" ResourceKey="SystemControlBackgroundBaseMediumBrush" />
                        </ResourceDictionary>
                        <ResourceDictionary x:Key="Dark">
                            <ResourceDictionary.MergedDictionaries>
                                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Themes/Dark.Blue.xaml"/>
                            </ResourceDictionary.MergedDictionaries>
                        </ResourceDictionary>
                    </ui:ThemeResources.ThemeDictionaries>
                </ui:ThemeResources>
`

**Comment by s77zz** [comment]
resoved
