### ISSUE TITLE
TabControl Styling

### ISSUE THREAD

**Issue by blakepell** [Kinnara/ModernWpf#5]
Fairly new to WPF so this is probably a newbie issue.  I was wanting to change the style of the TabControl to style them more like the UWP style.

1. My first attempt was to use Visual Studio to "Convert to a New Resource" and edit those styles.  This option was grayed out in Visual Studio.  Couldn't find a wait to "Edit Template" or "Convert to a New Resource"
2. My second attempt was to use the properties available in the XAML.  I could change the font there for instance, but not the font size oddly.  E.g. `<TabItem FontFamily="Courier New" FontSize="24">`
3. My third attempt was to have a resource on the page with a style with a TargetType set to TabItem.  This allowed me to change things like the FontSize but undid the rest of the stylings instead of just targeting the few styles I wanted to update (also, I could not change the "selected" styles this way).
4. My fourth attempt I brought the entire resource down from the libraries source but kept getting errors in the xaml on `xmlns:primitives="clr-namespace:ModernWpf.Controls.Primitives"` saying it couldn't access that namespace (when, I believe it did exist, I could reference those objects in the code behind anyway).

Beyond just changing colors, what is the best way to restyle a handful of properties from just a single control?

**Comment by Kinnara** [comment]
1. You'll need the latest preview version of VS for "Edit Template" to work (I tried 16.4.0 Preview 4.0).
2. The size of the tab item header text (as well as the icon) are controlled by resources that you can override.
3. Your style needs to be based on the default style in this library, like this:
```xaml
<Style TargetType="TabItem" BasedOn="{StaticResource DefaultTabItemStyle}">
    <Setter Property="FontFamily" Value="Courier New" />
</Style>
```
4. This one is correlated to the first one, because "Edit Template" handles this for you. To do it manually you can change all those `local:` and `primitives:` to `ui:`.

To make things clearer I just added a [basic customization example](https://github.com/Kinnara/ModernWpf/blob/master/ModernWpf.SampleApp/ControlPages/TabControlPage.xaml) to the sample app.

**Comment by blakepell** [comment]
You're awesome, thank you.  All of these tips help enormously.  I'll check the example out now.  I got something working that's styled similar to UWP, I'll probably start that over though and go with your methods and only change the pieces I need.

For posterity, here's what I came up with (UWP puts the selected border on top, I moved it to the bottom).  I had not finished trimming things out that weren't needed but thought I'd share nonetheless.

![image](https://user-images.githubusercontent.com/5958430/68893110-700d6600-06f2-11ea-9f5d-c95f08103ba0.png)

```
<TabControl SelectionChanged="TabControl_SelectionChanged">
    <TabControl.Resources>
        <Style  TargetType="{x:Type TabControl}">
            <Setter Property="Template">
                <Setter.Value>
                    <ControlTemplate TargetType="{x:Type TabControl}">
                        <Grid KeyboardNavigation.TabNavigation="Local">
                            <Grid.RowDefinitions>
                                <RowDefinition Height="Auto"/>
                                <RowDefinition Height="*"/>
                            </Grid.RowDefinitions>
                            <TabPanel 
                                Name="HeaderPanel"
                                Grid.Row="0"
                                Panel.ZIndex="1" 
                                Margin="0,0,0,0" 
                                IsItemsHost="True"
                                KeyboardNavigation.TabIndex="1"
                                Background="#222222" />
                            <Border 
                                Name="Border" 
                                Grid.Row="1" 
                                BorderThickness="0" 
                                CornerRadius="0" 
                                KeyboardNavigation.TabNavigation="Local"
                                KeyboardNavigation.DirectionalNavigation="Contained"
                                KeyboardNavigation.TabIndex="2">
                                <ContentPresenter 
                                  Name="PART_SelectedContentHost"
                                  Margin="4"
                                  ContentSource="SelectedContent" />
                            </Border>
                        </Grid>
                    </ControlTemplate>
                </Setter.Value>
            </Setter>
        </Style>
        <Style TargetType="TabItem">
            <Setter Property="Template">
                <Setter.Value>
                    <ControlTemplate TargetType="TabItem">
                        <Border Name="Border" BorderThickness="0,0,0,2" BorderBrush="#222222" CornerRadius="0,0,0,0" Margin="1,0,0,0">
                            <ContentPresenter x:Name="ContentSite"
                                VerticalAlignment="Center"
                                HorizontalAlignment="Center"
                                ContentSource="Header"
                                Margin="15,12"/>
                        </Border>
                        <ControlTemplate.Triggers>
                            <Trigger Property="IsEnabled" Value="True">
                                <Setter TargetName="ContentSite" Property="TextElement.FontFamily" Value="Segoe UI" />
                                <Setter TargetName="ContentSite" Property="TextElement.FontSize" Value="14" />
                                <Setter TargetName="ContentSite" Property="TextElement.FontWeight" Value="Bold" />
                            </Trigger>
                            <Trigger Property="IsSelected" Value="True">
                                <Setter TargetName="Border" Property="Background" Value="#171717" />
                                <Setter TargetName="Border" Property="BorderBrush" Value="#007ACC" />
                                <Setter TargetName="ContentSite" Property="TextElement.Foreground" Value="White" />
                            </Trigger>
                            <Trigger Property="IsSelected" Value="False">
                                <Setter TargetName="Border" Property="Background" Value="#222222" />
                                <Setter TargetName="ContentSite" Property="TextElement.Foreground" Value="Gray" />
                            </Trigger>
                        </ControlTemplate.Triggers>
                    </ControlTemplate>                        
                </Setter.Value>
            </Setter>
        </Style>
    </TabControl.Resources>
    <TabItem Header="Tab One" ui:ControlHelper.CornerRadius="0">
        <Label>This is the first tab.</Label>
    </TabItem>
    <TabItem Header="Tab Two" ui:ControlHelper.CornerRadius="0">
        <Label>This is the second tab.</Label>
    </TabItem>
    <TabItem Header="Tab Three" ui:ControlHelper.CornerRadius="0">
        <Label>This is the third tab.</Label>
    </TabItem>
</TabControl>
```

**Comment by Kinnara** [comment]
Thanks for sharing. It wasn't quite clear to me what you meant by "the UWP style" since the default style in this library is adapted from the WinUI TabView. After seeing your screenshot, it's clear that you were trying to make it look like the TabView in the UWP toolkit. Happy coding!

**Comment by blakepell** [comment]
That is correct, I've only ever used UWP with the Toolkit so I sometimes forget which controls are from where.  I'll go ahead and close this.

Thanks again for the advice.  This library is wonderful.
