### ISSUE TITLE
Cannot find resource named 'DefaultRepeatButtonStyle'. Resource names are case sensitive

### ISSUE THREAD

**Issue by s77zz** [Kinnara/ModernWpf#51]
When simple use v0.8.0 With Mahapps :
Cannot find resource named 'DefaultRepeatButtonStyle'. Resource names are case sensitive.	

![image](https://user-images.githubusercontent.com/20233712/77975981-44e88380-732e-11ea-88b7-a9b5ee154de2.png)

![image](https://user-images.githubusercontent.com/20233712/77977606-b62a3580-7332-11ea-8737-d5fb4c7a0db6.png)

**Comment by XamDR** [comment]
I also had a similar bug the other day while I was using Visual Studio. In my case it was when I tried to apply the `DefaulTextBoxStyle` to a custom TextBox. However, at runtime it worked fine and then the problem suddenly disappeared. It seems it's another case where the WPF designer just gets crazy lol.
