### ISSUE TITLE
Can you provide a compiled SampleApp application

### ISSUE THREAD

**Issue by Rosalina129** [Kinnara/ModernWpf#544]
Well, I have a WPF project that uses this NuGet extension, but I really don't know how to use this extension component, and you don't have a pre-compiled example application for reference. I think this component is quite good, but it is too difficult to get started, so could you please provide some simple and easy to use examples for reference?

Maybe my English is not that good, so all the translations, the following is the original Chinese words:
是这样的，我有一个 WPF 项目，使用了这个 NuGet 扩展，但是我实在不知道这个扩展组件怎么用，而且你这里也没有预先编译好的实例应用可供参考，我感觉这个组件还算不错，但是上手难度太大了，所以可不可以提供一些比较简单易用的实例以供参考？

**Comment by SioGabx** [comment]
Hi,
You can find attached a compiled version of the sample application.

[ModernWpf.SampleApp_net5.0-windows10.0.18362.0.zip](https://github.com/Kinnara/ModernWpf/files/10098804/ModernWpf.SampleApp_net5.0-windows10.0.18362.0.zip)

**Comment by Rosalina129** [comment]
Ok, thanks for the offer
