### ISSUE TITLE
 (Feature Request) Tabs draggable/dockable and with close Button

### ISSUE THREAD

**Issue by daniel-rck** [Kinnara/ModernWpf#55]
The Tabs look nice, but you can't really interact with them like here for example: https://github.com/ButchersBoy/Dragablz

**Comment by Kinnara** [comment]
Will a WinUI-like style for Dragablz be good enough?

**Comment by daniel-rck** [comment]
That would be great!

**Comment by Kinnara** [comment]
[Here ](https://github.com/Kinnara/ModernWpf/tree/master/samples/DragablzSample) it is. Rather basic but hopefully not too bad for a start.

![Dragablz Demo](https://user-images.githubusercontent.com/1617766/79205268-4490d200-7e70-11ea-8d4d-7754aa092cbe.gif)

**Comment by daniel-rck** [comment]
Wow, this looks really nice, I'll give it a try, thank you!
