### ISSUE TITLE
(Question) Windows theme instead of App Theme?

### ISSUE THREAD

**Issue by mikecoxlong** [Kinnara/ModernWpf#56]
I want to know if there is a way to get the **Windows Theme** (I'm talking about the **Light theme** introduced in Windows 10 1903) instead of the **App Theme**
![image](https://user-images.githubusercontent.com/62238099/78755719-3dad1f80-7997-11ea-9964-7b6190a5b71d.png)

FluentWPF supports it
```cs
        private static WindowsTheme GetWindowsTheme()
        {
            var regkey = Microsoft.Win32.Registry.CurrentUser.OpenSubKey(@"Software\Microsoft\Windows\CurrentVersion\Themes\Personalize", false);
            // キーが存在しないときはnullが返る
            if (regkey == null) return WindowsTheme.Light;
            var intValue = (int)regkey.GetValue("SystemUsesLightTheme", 1);

            return intValue == 0 ? WindowsTheme.Dark : WindowsTheme.Light;
        }
```

FluentWPF is also a great library but I don't want to include both libraries in a single application which may cause design flaws (multiple styles and themes intercepting). 

I can use this particular code from FluentWPF and handle ThemeManager to follow the **Windows Theme**. But it would be great if it's included in ModernWpf

Is there a way to access it in your library? Is there any plan to add it in the future?

**Comment by Kinnara** [comment]
I believe [this answer](https://github.com/Kinnara/ModernWpf/issues/9#issuecomment-557579356) still applies. Once that's done, the app should follow the Windows theme. Internally WinRT APIs are used to get the Windows theme and listen to theme changes.

**Comment by mikecoxlong** [comment]
I talking the about the **Theme applied to Start Menu, Action Center and Task Bar** not the theme applied to **Applications**. My app follows the **System App Theme** (I have app.manifest) not the **System Windows Theme**. Any Idea?

**Comment by mikecoxlong** [comment]
And another question, How does your library consume **WinRT** APIs and work on Windows versions that doesn't have it? Is it because of adding this attribute `        [MethodImpl(MethodImplOptions.NoInlining)]` or the `app.manifest` file?
I'm desperate for my app to include WinRT APIs and run on older windows versions

**Comment by Kinnara** [comment]
> I talking the about the **Theme applied to Start Menu, Action Center and Task Bar** (the first option in the image) not the theme applied to **Applications**. My app follows the **System App Theme** (I have app.manifest) not the **System Windows Theme**. Any Idea?

Since there isn't a built-in way to get the Windows theme or follow it in UWP, and this library tries to stay within the boundaries of what's possible in UWP, currently there's no plan to add this feature.

> And another question, How does your library consume **WinRT** APIs and work on Windows versions that doesn't have it? Is it because of adding this attribute ` [MethodImpl(MethodImplOptions.NoInlining)]` or the `app.manifest` file?
> I'm desperate for my app to include WinRT APIs and run on older windows versions

There may be better ways, but `[MethodImpl(MethodImplOptions.NoInlining)]` does the trick.

**Comment by mikecoxlong** [comment]
> Since there isn't a built-in way to get the Windows theme or follow it in UWP, and this library tries to stay within the boundaries of what's possible in UWP, currently there's no plan to add this feature.

Thanks for your clarification. I respect your opinion and work. And Thanks again for this wonderful library
