### ISSUE TITLE
Use thicker default stroke for RadioButton, Checkbox, ToggleSwitch etc.

### ISSUE THREAD

**Issue by akdevservices** [Kinnara/ModernWpf#58]
Use thicker default stroke for RadioButton, Checkbox, ToggleSwitch etc. to make these controls consistent with Windows UI.

Windows 10 UI:
![image](https://user-images.githubusercontent.com/29972256/78879725-f5583500-7a5c-11ea-8ebb-48066e4df7f7.png)

ModernWpf:
![image](https://user-images.githubusercontent.com/29972256/78879942-49631980-7a5d-11ea-9e83-1c6bcb78a3e1.png)
![image](https://user-images.githubusercontent.com/29972256/78880357-f3db3c80-7a5d-11ea-81a5-816cadfeac0d.png)

**Comment by Kinnara** [comment]
"Default controls were updated to reduce the outlines to be thinner for a cleaner and familiar look" in [WinUI 2.2](https://docs.microsoft.com/en-us/uwp/toolkits/winui/release-notes/winui-2.2#b-border-thickness-update).

**Comment by akdevservices** [comment]
Thank you for clarification. Though I don't understand why Microsoft is doing such things, customers want to see the app "looking exactly like Windows". Is it possible to make some optional "compatibility mode" to have the latest ModernWpf using "old" controls rendering until Microsoft changes Windows 10 UI?

**Comment by akdevservices** [comment]
It's funny, that Microsoft uses "old" controls rendering in Windows UI Library 2.3 Release notes.
https://docs.microsoft.com/en-us/uwp/toolkits/winui/release-notes/winui-2.3

![image](https://user-images.githubusercontent.com/29972256/78884014-f3917000-7a62-11ea-9901-1f1be346d94d.png)

**Comment by Kinnara** [comment]
[Overriding XAML resources](https://github.com/Kinnara/ModernWpf/issues/2#issuecomment-547381118) with their "old" values should get you pretty far. [Here](https://github.com/Kinnara/ModernWpf/blob/master/ModernWpf.SampleApp/Presets/PreFluent.xaml)'s a non-exhaustive list of resources to override. To make some controls (like RadioButton) match exactly you'll also need to override the corresponding theme brushes.

**Comment by akdevservices** [comment]
New PreFluent.xaml in SampleApp makes it simple as copy/pasting a dictionary and merging it in the app. Perfect.

Thanks a lot for your great work.
