### ISSUE TITLE
How can I get a ContentDialog's result?

### ISSUE THREAD

**Issue by niubizi** [Kinnara/ModernWpf#6]
I tried to get a ContentDialog's result like this, but it's not working.
```c#
var dlg = new MyContentDialog();
var t = dlg.ShowAsync();
if (t.Result == ContentDialogResult.Primary)
{
    // do something
}
```

**Comment by Kinnara** [comment]
You need to `await` the `Task` returned by `ShowAsync()` to get the result, like this:
```cs
private async void ShowDialog(object sender, RoutedEventArgs e)
{
    var dlg = new ContentDialog
    {
        PrimaryButtonText = "Yes",
        SecondaryButtonText = "No"
    };
    var result = await dlg.ShowAsync();
    if (result == ContentDialogResult.Primary)
    {
        // do something
    }
}
```
For more information you may want to read [Task-based asynchronous pattern (TAP)](https://docs.microsoft.com/en-us/dotnet/standard/asynchronous-programming-patterns/task-based-asynchronous-pattern-tap) or the [Chinese version](https://docs.microsoft.com/zh-cn/dotnet/standard/asynchronous-programming-patterns/task-based-asynchronous-pattern-tap) if you prefer.

**Comment by niubizi** [comment]
This is very helpful, thank you.
