### ISSUE TITLE
Not really an issue, perhaps just a note...

### ISSUE THREAD

**Issue by punker76** [Kinnara/ModernWpf#65]
Why just copy and paste all the good stuff from other repositories without offering at least a little help with them or making improvements to it?

**Comment by Kinnara** [comment]
Apart from something that makes it simple to modernize WPF apps, personally I see this library also as a bridge to WinUI and try to make it relatively effortless to eventually transition to WinUI. This requires high compatibility with WinUI both in API and behavior, so naturally a large portion of the code was ported from there. And I do contribute to WinUI as well.

**Comment by punker76** [comment]
I did not only mean WinUI, what about the other 3rd party libs? I did not see any contributions to it... sorry

**Comment by Kinnara** [comment]
Can you be more exact? There are some controls (in ModernWpf.MahApps) that are dependent on MahApps.Metro, but except for a few internal members (to avoid reflection) and a rather small portion of the original control templates (to ensure the template parts are present and some properties are correctly set), not much was copy-pasted.

**Comment by punker76** [comment]
Maybe I was too hard, but some changes were good enough to bring back to the original repo. I saw the SplitView and some other commits... but ok, let it as it is.

**Comment by Kinnara** [comment]
I do agree that some additions to the HamburgerMenu could be brought back to MahApps. I have to clarify about SplitView though: expect for the XAML (which is adapted from WinUI), it's a completely original implementation against the latest UWP API and doesn’t really have an original repo.
