### ISSUE TITLE
SplitView with IsPaneOpen set to False and DisplayMode set to CompactInline glitching out

### ISSUE THREAD

**Issue by TheXamlGuy** [Kinnara/ModernWpf#67]
To repro this issue you will need to set IsPaneOpen property to False and DisplayMode property to CompactInline. Debug the application and you will see that the pane is open even though you have specified it to be closed set via the IsPaneOpen property earlier, and if you toggle the pane to open, you will see it will double glitch the animation.

Example `code:

```
<ui:SplitView IsPaneOpen="{Binding ElementName=togglePaneButton, Path=IsChecked, Mode=TwoWay}" DisplayMode="CompactInline" />
<ToggleButton  x:Name="togglePaneButton" IsChecked="False" Content="IsPaneOpen" />
```

I've attached a gif of the animation glitch when toggling the Pane for the first time.
![compactmode1](https://user-images.githubusercontent.com/14894973/79685195-a6658900-822e-11ea-9077-2435e3d38465.gif)

**Comment by Kinnara** [comment]
Thanks for the detailed bug report. It's now fixed in v0.8.3.
