### ISSUE TITLE
NavigationView 

### ISSUE THREAD

**Issue by ghost1372** [Kinnara/ModernWpf#7]
If possible please add NavigationView
There's an example [here](https://github.com/manuelroemer/Celestial.UIToolkit#15-the-control-gallery)

![image](https://user-images.githubusercontent.com/9213496/68942918-027b3b80-07bf-11ea-8bd2-2b4405b5f55e.png)

**Comment by Kinnara** [comment]
I won't say it's impossible to add the NavigationView but it will be a lot of work and won't be done anytime soon. For now, does the MahApps HamburgerMenu satisfy some of your needs? In case you haven't noticed, I have an [integration library for MahApps](https://github.com/Kinnara/ModernWpf/tree/master/ModernWpf.MahApps) in the works and it looks like this:

![MapApps Integration](https://github.com/Kinnara/ModernWpf/raw/master/docs/images/MahApps.png)

BTW, I didn't know the library you linked existed, thanks for sharing.
