### ISSUE TITLE
Number box overrides correct input 

### ISSUE THREAD

**Issue by nlogozzo** [Kinnara/ModernWpf#71]
Hi all, 
I'm using a number box control in one of my applications where I can only accept numbers. However, when I enter a number in the box and press Ctrl+S to save it, the number gets erased as if I entered letters. The way I handle shortcuts in my program is 
```Csharp
var cmdSaveTag = new RoutedCommand();
cmdSaveTag.InputGestures.Add(new KeyGesture(Key.S, ModifierKeys.Control));
CommandBindings.Add(new CommandBinding(cmdSaveTag, BtnSaveTagClick));
```
Maybe that could be it?
Thanks in advanced

**Comment by Kinnara** [comment]
I recall seeing a similar issue on the WinUI repo. Will look into this.

**Comment by Kinnara** [comment]
Usually the input is not validated or committed until the enter key is pressed or the number box loses focus, but there's a trick to force the input to be validated while keeping the focus within the control by temporarily changing the `ValidationMode`:
```cs
myNumberBox.ValidationMode = NumberBoxValidationMode.Disabled;
myNumberBox.ValidationMode = NumberBoxValidationMode.InvalidInputOverwritten;
```

**Comment by nlogozzo** [comment]
That worked. Thanks
