### ISSUE TITLE
ContentDialog doesn't seem to measure properly with hidden elements

### ISSUE THREAD

**Issue by Deadpikle** [Kinnara/ModernWpf#74]
## Environment

* ModernWPF 0.8.3
* Visual Studio 16.5
* .NET Framework 4.8

## Bug description

I've got an issue where my `ContentDialog` doesn't render properly if I have some initially-hidden elements. A picture explains it better than words. Basically, I have an error message label that's hidden that I only want to show if there's an error. However, even if I make the `ContentDialog` scrollable via a style, the scroll bar doesn't show up.

![screenshot](https://user-images.githubusercontent.com/5092399/79984260-eae36580-8476-11ea-81c6-47ed78f554e7.png)

Style for scrollable (taken from demo):

```
<Style x:Key="ScrollableContentDialogStyle" TargetType="ui:ContentDialog">
    <Setter Property="ScrollViewer.VerticalScrollBarVisibility" Value="Auto" />
    <Style.Resources>
        <Thickness x:Key="ContentDialogContentMargin">24,0,24,0</Thickness>
        <Thickness x:Key="ContentDialogContentScrollViewerMargin">-24,0,-24,0</Thickness>
        <Thickness x:Key="ContentDialogTitleMargin">24,0,24,12</Thickness>
    </Style.Resources>
</Style>
```

I realize there is a maximum dialog height, but shouldn't the scrollbar kick in at that point?

## Reproducible sample

https://github.com/Deadpikle/ModernWPF-ContentDialog-MeasureBug

I removed all my bindings and such from the sample to keep it simple.

Thank you for any help you can provide!

**Comment by Kinnara** [comment]
Thanks for the detailed report and the repro! Turns out to be caused by a bug in SimpleStackPanel. I'll probably publish a new package just for this since the stack panel is quite essential.

**Comment by Deadpikle** [comment]
Oh, thanks for the quick turnaround on a fix! I appreciate it. :)

Going ahead and closing this since I see the commit is pushed. Thanks again.
