### ISSUE TITLE
Button padding and content cropping

### ISSUE THREAD

**Issue by milos12345** [Kinnara/ModernWpf#76]
I am not sure if this is intentional but I expected the text not be be cropped like this if I need to create smaller buttons by adjusting the Height property. 
![image](https://user-images.githubusercontent.com/5231547/80267765-b76c2b00-8670-11ea-8b5a-42f8ea0b585e.png)
I then thought the Compact Size option in the sample app will also make buttons smaller but these remained unchanged. 

Additional question about the colors: it seems that button background is SystemControlBackgroundBaseLowBrush which is then SystemBaseLowColor that has an value of #33000000. Is that also from Windows design guidelines as it seems unnecessary to add transparency and affect performance.

**Comment by nik9play** [comment]
Set Padding property of button to different value.
For ex. i set it to 0:
![изображение](https://user-images.githubusercontent.com/13693620/80282092-35374180-8718-11ea-854e-ca1efbb38919.png)

**Comment by Kinnara** [comment]
The colors match [those in UWP](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/xaml-theme-resources#light-and-dark-theme-colors). If you'd like to avoid transparency, they can be easily overridden using [ColorPaletteResources](https://github.com/Kinnara/ModernWpf/wiki/Common-Tasks#override-predefined-colors).

**Comment by milos12345** [comment]
Thank you. I modified it by cloning original Button template and in `<Style TargetType="{x:Type Button}">` changing padding so it affects all buttons. My suggestion is to make bottom/top padding zero as default to avoid cropping; or to have Compact Size option also modify the button size.
I was not aware of ColorPaletteResources; that seems an elegant solution.
