### ISSUE TITLE
NavigationView - SelectionIndicator and go to settings page do not work

### ISSUE THREAD

**Issue by ORRNY66** [Kinnara/ModernWpf#78]
Hi, I really like NavigationView but I noticed a few bugs.
1) SelectionIndicator does not work if I go from PaneDisplayMode Top to Left and back.
2) In PaneDisplayMode Top, going to the settings page does not work.
Thanks so much for your work.
![gif23](https://user-images.githubusercontent.com/5471789/80306234-463c8d00-87c2-11ea-883a-3dcc23781583.gif)

**Comment by Kinnara** [comment]
Thanks for reporting. I'll try to address these together with a few other known issues of NavView in an upcoming release.

**Comment by Kinnara** [comment]
1. Fixed by 392523474a171ee4a0f2616e6555d1b67e840519.
2. Fixed by fa446fe154469ae0d4c5009fac9181eabe07f999.
