### ISSUE TITLE
CheckBox too far left in SfTreeGridCheckBoxColumn using ModernWpfUi

### ISSUE THREAD

**Issue by Lilium-Candidum** [Kinnara/ModernWpf#79]
Hello,

I am using controls from Syncfusion, one of them is the SfTreeGrid. Everything works fine, but when I implement the ModernWpfUi in my project, the SfTreeGridCheckBoxColumn shows the Checkbox is too far left and even setting the alignment to "right" does not work.

![SfTreeGridCheckBoxColumn](https://user-images.githubusercontent.com/48719795/80338966-f8756280-885d-11ea-9639-f86f0616050d.png)

**Comment by Lilium-Candidum** [comment]
Here is a sample project:

[GridTextColumnSample-370447964.zip](https://github.com/Kinnara/ModernWpf/files/4539185/GridTextColumnSample-370447964.zip)

**Comment by Kinnara** [comment]
It's caused by the `MinWidth` defined in the CheckBox's default style. You can use the following code to remove it:
```xaml
<syncfusion:SfTreeGrid>
    <syncfusion:SfTreeGrid.Resources>
        <Style TargetType="CheckBox" BasedOn="{StaticResource DefaultCheckBoxStyle}">
            <Setter Property="MinWidth" Value="0" />
        </Style>
    </syncfusion:SfTreeGrid.Resources>
</syncfusion:SfTreeGrid>
```

**Comment by Lilium-Candidum** [comment]
Thank you, it works now!
