### ISSUE TITLE
Navigation View - SelectionIndicator looks broken 

### ISSUE THREAD

**Issue by Evheni** [Kinnara/ModernWpf#83]
![2020-04-30-20-37-15](https://user-images.githubusercontent.com/15703832/80774606-1b846880-8b23-11ea-9918-624815b170de.gif)

**Comment by Kinnara** [comment]
I haven't seen this exact behavior but I did observe flicker from time to time. I've made some changes to try to eliminate the flicker. Not sure if they'll help with this though.

**Comment by Evheni** [comment]
Just tried it out with the latest code, looks fine.
