### ISSUE TITLE
Flyout moves to the upper left corner of the screen when clicking button inside

### ISSUE THREAD

**Issue by murermader** [Kinnara/ModernWpf#85]
I really have no idea whats going on. This is what happens: [youtube link](https://youtu.be/9dIeCPMg8yE)

The code in question looks like this, I basically just copied it from a sample:

```XML
            <Button Margin="0 0 10 0" Content="Cancel">
                <ui:FlyoutService.Flyout>
                    <ui:Flyout>
                        <StackPanel>
                            <TextBlock Margin="0 0 0 12" Text="All changes will be discarded. Do you want to continue?" />
                            <Button Command="{Binding Path=CmdCancel}" Content="Yes, discard changes" />
                        </StackPanel>
                    </ui:Flyout>
                </ui:FlyoutService.Flyout>
            </Button>
```

The Cancel button replaces the current view (with the Flyout in it) with another view (both inside a content presenter). Maybe this is causing the issue. Also the button in the flyout becomes unresponsive.

---
### Some additional info

Tested on both `stable 0.8.3` and `0.9.0-preview.200425.2` (same behaviour on both)
Target Framework is `.NET 4.7.2`

**Comment by Kinnara** [comment]
Do you need the flyout to stay open after the button is clicked?

**Comment by murermader** [comment]
No the flyout should close, after the button inside is pressed. Am I supposed to manually close the flyout after pressing the button in the flyout? If so, how would I do that?

**Comment by Kinnara** [comment]
You can close the flyout by calling its Hide method.

**Comment by murermader** [comment]
OK thank you for answering. I could do it by calling the Hide method, although by not abiding the MVVM pattern. Guess this solution is good!
