### ISSUE TITLE
Multi-Thread application

### ISSUE THREAD

**Issue by davidsisques** [Kinnara/ModernWpf#86]
I'm triying your library and everything works OK when all the windows of the application run in the same thread, but if i open a window in another thread i get the next error:

"Cannot access Freezable 'System.Windows.Shell.WindowChrome' across threads because it cannot be frozen"

I think it may be because this new window tries to acces a shared resource, but i dont know hoy to avoid this. Is there any way to make it work?
Thanks

**Comment by tedd** [comment]
This is by design in almost any UI application framework, including WPF. Google cross thread wpf for information. The solution is to use Dispatch for executing UI-related work. See [Dispatcher documentation](https://docs.microsoft.com/en-us/dotnet/api/system.windows.threading.dispatcher).

Every control will have a Dispatcher object on it, so just use that to execute any UI action. A quick google found this article that explains it: https://www.koskila.net/using-dispatcher-to-update-values-in-gui-elements-from-a-background-thread/

**Comment by davidsisques** [comment]
Thanks, but this is my problem. It is when creating a new window that runs on a non main thread. Here is the code im using: 
private void OnCreateNewWindow(object sender, RoutedEventArgs e)
        {
            Thread thread = new Thread(() =>
            {
 
                Window1 w = new Window1();
                w.Show();
                 
                System.Windows.Threading.Dispatcher.Run(); 

            });
            thread.SetApartmentState(ApartmentState.STA);
            thread.Start();
        }

**Comment by Kinnara** [comment]
"[Multiple Windows, Multiple Threads](https://docs.microsoft.com/en-us/dotnet/framework/wpf/advanced/threading-model#multiple-windows-multiple-threads)" is a valid scenario in WPF. Unfortunately there are multiple known issues when using this library in such an application. I'll try to create a sample and see how far we can get without making major changes.

**Comment by Kinnara** [comment]
Added some support for this scenario. Certain features (e.g. setting ThemeManager.AccentColor) don't work yet, but for the most part it seems to work fine.

**Comment by davidsisques** [comment]
Thank you very much.

I downloaded the updated version but i cant compile it, Visual Studio fails to open the projects, could you upload a compiled version?

Sorry for the inconvenience.

**Comment by Kinnara** [comment]
You were probably missing the .NET Core SDK. I'll try to release a new preview this week.

**Comment by davidsisques** [comment]
Ok, I'll wait for It.
Thanks

Enviado desde Outlook Mobile<https://aka.ms/blhgte>

________________________________

**Comment by Kinnara** [comment]
A new preview has been released. Set ThemeResources.CanBeAccessedAcrossThreads to true to enable support for multiple UI threads.

**Comment by unofficialdev** [comment]
@davidsisques Can this work with UserControl or Control? Each Control a separate thread.
