### ISSUE TITLE
FontIcons with glyph name instead of code

### ISSUE THREAD

**Issue by daniel-rck** [Kinnara/ModernWpf#93]
Hello, is there any option to write the name of the glyph instead of the code?
e.g.

````
<ui:FontIcon Glyph="&#xE70F;" />

<ui:FontIcon Glyph="Edit" />
````

**Comment by ShankarBUS** [comment]
_(I'm not sure)_ UWP has this same behaviour, see [**FontIcon.Glyph**](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.fonticon.glyph). _(You may know)_ You'll need to use **[SymbolIcon](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.symbolicon)**, it has a **[Symbol](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.symbol)** property which may suit your need _(but it is limited)_

**Comment by daniel-rck** [comment]
Isn't SymbolIcon UWP-only?

**Comment by ShankarBUS** [comment]
> Isn't SymbolIcon UWP-only?

[**SymbolIcon**](https://github.com/Kinnara/ModernWpf/blob/master/ModernWpf/Controls/SymbolIcon.cs) and [**Symbol** ](https://github.com/Kinnara/ModernWpf/blob/master/ModernWpf/Controls/Symbol.cs) are available within this library.

> Note: Based on pull #92, **SymbolIcon** and other **IconElements** are going to be moved from **ModernWpf.Controls** → **ModernWpf.IconElement** Namespace, make sure you use the correct namespace

[And also other **IconElements** such as **BitmapIcon** and **PathIcon** are also available in this lib](https://github.com/Kinnara/ModernWpf/wiki/Controls#additional-controls)

**Comment by daniel-rck** [comment]
Thank you for your explanation, unfortunately SymbolIcon doesn't contain all Symbols that are available as FontIcon-Glyphs. I'll stay with Glyph-Codes...

**Comment by Kinnara** [comment]
Just to clarify, the IconElement-related files were moved to a separate folder in that PR, but their namespace were not changed.

**Comment by ShankarBUS** [comment]
@Kinnara, oh sorry my bad

**Comment by Kinnara** [comment]
@ShankarBUS No worries at all. Thanks for answering the questions!

**Comment by ShankarBUS** [comment]
Hey @daniel-rck, I've kinda found the solution. Basically you can **Extend** the **FontIcon** control to suit your need like this ⬇️ 

```cs
public class FontIconEx : FontIcon
{
    static FontIconEx()
    {
        GlyphProperty.OverrideMetadata(typeof(FontIconEx), new FrameworkPropertyMetadata(string.Empty, OnGlyphChanged));
    }

    private static void OnGlyphChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
    {
        var fontIconEx = (FontIconEx)d;
        if (fontIconEx._textBlock2 != null)
        {
            fontIconEx._textBlock2.Text = GetGlyph((string)e.NewValue);
        }
    }

    private TextBlock _textBlock2;

    private protected override void InitializeChildren()
    {
        _textBlock2 = new TextBlock
        {
            Style = null,
            HorizontalAlignment = HorizontalAlignment.Stretch,
            VerticalAlignment = VerticalAlignment.Center,
            TextAlignment = TextAlignment.Center,
            FontFamily = FontFamily,
            FontSize = FontSize,
            FontStyle = FontStyle,
            FontWeight = FontWeight,
            Text = GetGlyph(Glyph)
        };

        if (ShouldInheritForegroundFromVisualParent)
        {
            _textBlock2.Foreground = VisualParentForeground;
        }

        typeof(FontIcon).GetField("_textBlock", BindingFlags.NonPublic | BindingFlags.Instance).SetValue(this, _textBlock2);

        Children.Add(_textBlock2);
    }

    private static string GetGlyph(string value)
    {
        if (Enum.TryParse(value, true, out Symbol symbol))
        {
            return ConvertToString(symbol);
        }
        else
        {
            return value;
        }
    }
    private static string ConvertToString(Symbol symbol)
    {
        return char.ConvertFromUtf32((int)symbol).ToString();
    }
}
```

This **FontIconEx** control will parse and display every _Symbol_ like the **SymbolIcon** control and also display _Glyph Codes_ like the **FontIcon** control.

Thus you can do both 

> (You may already know) Note: If you enter text which are neither **_Symbol names_** nor **_Glyph Codes_** those text will appear as boxes

```xaml
<local:FontIconEx Glyph="&#xE70F;" />

<local:FontIconEx Glyph="Edit" />
```
--------
If the existing **Symbols** are not enough for you, you can create a new enum called  **SymbolEx** with additional glyphs having custom names. Like this ⬇️ 

```cs
public enum SymbolEx
{
    // Copy paste the member form Symbol enum here
    Airplane = 59145,
    Book = 59190,
    HardDrive = 60834,
    // And other custom glyphs goes down here
}
```
and change _Symbol_ to _SymbolEx_ in the **GetGlyph** and **ConvertToString** methods inside the **FontIconEx** class.

**Comment by ShankarBUS** [comment]
Hey @daniel-rck, I have updated the code and it works fine even in designer 👍,

Try this snippet
```xaml
<ui:CommandBar>
    <ui:AppBarButton>
        <ui:AppBarButton.Icon>
            <local:FontIconEx Glyph="Cancel"/>
        </ui:AppBarButton.Icon>
    </ui:AppBarButton>
    <ui:AppBarButton>
        <ui:AppBarButton.Icon>
            <local:FontIconEx Glyph="&#xE70F;"/>
        </ui:AppBarButton.Icon>
    </ui:AppBarButton>
</ui:CommandBar>
```
which produce this ⬇️

![image](https://user-images.githubusercontent.com/63704247/84164378-14406b00-aa90-11ea-8abf-8ca0bd6a0217.png)

**Comment by daniel-rck** [comment]
Nice work. Will give it a try next time.
