### ISSUE TITLE
Navigation View - Settings item property

### ISSUE THREAD

**Issue by vessd** [Kinnara/ModernWpf#94]
Is there a way to rename the settings item? For localization.

**Comment by Kinnara** [comment]
There doesn't seem to be a supported way to do this. Based on the current implementation, the following should work:
```cs
public class NavigationViewEx : NavigationView
{
    protected override void OnPropertyChanged(DependencyPropertyChangedEventArgs e)
    {
        base.OnPropertyChanged(e);

        if (e.Property == SettingsItemProperty)
        {
            OnSettingsItemChanged(e);
        }
    }

    private void OnSettingsItemChanged(DependencyPropertyChangedEventArgs e)
    {
        if (e.NewValue is NavigationViewItem settingsItem)
        {
            // Customize the settings item
        }
    }
}
```

**Comment by wmrutten** [comment]
FYI, I have managed to generate a custom ModernWPF resource string library to support an additional language.

1) Create a new copy of the original string resource file from the ModernWPF repository:
   `".\ModernWpf\Resources\Strings.resx"`
   Rename the copy to `"ModernWpf.Resources.Strings.[language].resx"`, where `[language]` represents a language code.
   Add the new resource file to your own project, e.g. in the `\Properties` folder
   Example: `".\Properties\ModernWpf.Resources.Strings.nl.resx"`
   Translate the original resource strings to the new language, e.g. using the Visual Studio Resource Editor.

2) Add a post-build step to manually generate a resource assembly
   Reference the original `"ModernWpf.dll"` assembly as a template.

   ```
   REM Path to (SDK) folder containing ResGen.exe and Al.exe
   SET WindowsSDK_ExecutablePath_x64=C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8 Tools\
   
   "%WindowsSDK_ExecutablePath_x64%\resgen.exe" "Properties\ModernWpf.Resources.Strings.nl.resx" "$(IntermediateOutputPath)ModernWpf.Resources.Strings.nl.resources"
   "%WindowsSDK_ExecutablePath_x64%\al.exe" -target:lib -embed:"$(IntermediateOutputPath)ModernWpf.Resources.Strings.nl.resources" -culture:nl -out:"$(TargetDir)nl\ModernWpf.resources.dll" -template:"$(TargetDir)ModernWpf.dll"
   ```

   Build your project.
   Visual Studio should generate an additional resource assembly for ModernWpf in a new subfolder of the output directory, e.g. `".\nl\ModernWpf.resources.dll"`.
   
3) Implement custom logic to initialize/toggle ModernWpf resource manager culture
   
   Small problem: the `ModernWpf.Strings` resource file is `internal`, not `public`.
   We can use reflection to update the ModernWpf resource manager culture.
   
   ```   
   var resourcesTypeName = $"{nameof(ModernWpf)}.Strings";
   var asm = typeof(ModernWpf.ApplicationTheme).Assembly;
   if (asm.GetType(resourcesTypeName) is Type resourcesType)
   {
       var setCulturePropInfo = resourcesType.GetProperty(
   		nameof(WinUIApp.Properties.Resources.Culture),
   		BindingFlags.NonPublic | BindingFlags.Static | BindingFlags.SetProperty);
       setCulturePropInfo?.SetValue(null, culture);
   }
   ```

4) Note: the ModernWpf implementation logic caches some localization string resources
   You may have to reload control or toggle some state to force invalidation.
   For example, NavigationView hamburger button tooltip is reset/re-assigned on pane open/close.

Hope this helps,

Michel

**Comment by vessd** [comment]
After the last update (0.9.0-preview.200515.2), the problem is no longer relevant to me. I think it can be closed.
