### ISSUE TITLE
Clicking a combobox results in NullReferenceException

### ISSUE THREAD

**Issue by shankarsan93** [Kinnara/ModernWpf#99]
Hi,

First of all, I would like to say that you have done an excellent job with this library. I just love the way each and every element looks.

Now, coming to the issue I am facing. I am using powershell to make a wpf gui app and when clicking any of the ComboBox objects I get an error as below:

'Exception calling "ShowDialog" with "0" argument(s): "Object reference not set to an instance of an object."'

This is strange in that its pointing towards the ShowDialog() method but it only occurs when clicking  a ComboBox. I have tried running the same code without your library in the default WPF settings and its working fine. So I believe that something in your library might be causing this issue.

Could you please check and fix this or assist me with how to do it right ? I am pasting my code below for your reference.

Powershell Code
------------------
Add-Type -AssemblyName PresentationFramework
[Reflection.Assembly]::LoadFrom('E:\Scripts\VS Code\Powershell\Har_Reader\System.ValueTuple.dll') | Out-Null
[Reflection.Assembly]::LoadFrom('E:\Scripts\VS Code\Powershell\Har_Reader\ModernWpf.dll') | Out-Null

[xml]$xml = @'
<Window
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:ui="http://schemas.modernwpf.com/2019"
    ui:WindowHelper.UseModernWindowStyle="False"
    Title="HAR Reader" Height="700" Width="1270">
    <Window.Resources>
        <ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>
                <ui:ColorPaletteResources Accent="#FF0078D7" />
                <ResourceDictionary Source="pack://application:,,,/ModernWpf;component/ThemeResources/Light.xaml" />
                <ResourceDictionary Source="pack://application:,,,/ModernWpf;component/ControlsResources.xaml" />
            </ResourceDictionary.MergedDictionaries>
        </ResourceDictionary>
    </Window.Resources>
<Grid>
<Grid.ColumnDefinitions>
    <ColumnDefinition Width="260*"/>
    <ColumnDefinition Width="161*"/>
</Grid.ColumnDefinitions>
<ComboBox Name="Filter_ComboBox" HorizontalAlignment="Left" VerticalAlignment="Bottom" Margin="10" Width="100" Height="22">
    <ComboBoxItem Content="Filter"/>
    <ComboBoxItem Content="Response Code"/>
    <ComboBoxItem Content="Method"/>
</ComboBox>
<ComboBox Name="Operator_ComboBox" HorizontalAlignment="Left" Margin="120,0,0,10.255" VerticalAlignment="Bottom" Height="22" Width="80">
    <ComboBoxItem Content="Like"/>

    <ComboBoxItem Content="Not Like"/>
</ComboBox>
<TextBox Name="Filter_TextBox" HorizontalAlignment="Left" Margin="210,0,0,10.255" TextWrapping="NoWrap" VerticalAlignment="Bottom" Width="319" Height="22"/>
</Grid>
</Window>
'@

$SyncHash = [HashTable]::Synchronized(@{})
$SyncHash.Window = [Windows.Markup.XamlReader]::Load(([System.Xml.XmlNodeReader]::new($xml)))
$xml.SelectNodes("//*[@Name]") | ForEach-Object {
    $SyncHash.$($_.Name) = $SyncHash.Window.FindName($_.Name)
}

$SyncHash.Window.ShowDialog()

PS:- I have tried using the v0.83 library and the latest alpha version as well. Having this issue in both of them.

Hope you will be able to help. Thanks in advance. :-)

![ComboBox Error](https://user-images.githubusercontent.com/56706618/82608911-22117780-9bd9-11ea-9c80-dca2bd96c390.PNG)

**Comment by shankarsan93** [comment]
<Window
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:ui="http://schemas.modernwpf.com/2019"
    ui:WindowHelper.UseModernWindowStyle="False"
    Title="HAR Reader" Height="700" Width="1270">
    <Window.Resources>
        <ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>
                <ui:ColorPaletteResources Accent="#FF0078D7" />
                <ResourceDictionary Source="pack://application:,,,/ModernWpf;component/ThemeResources/Light.xaml" />
                <ResourceDictionary Source="pack://application:,,,/ModernWpf;component/ControlsResources.xaml" />
            </ResourceDictionary.MergedDictionaries>
        </ResourceDictionary>
    </Window.Resources>
<Grid>
<Grid.ColumnDefinitions>
    <ColumnDefinition Width="260*"/>
    <ColumnDefinition Width="161*"/>
</Grid.ColumnDefinitions>
<ComboBox Name="Filter_ComboBox" HorizontalAlignment="Left" VerticalAlignment="Bottom" Margin="10" Width="100" Height="22">
    <ComboBoxItem Content="Filter"/>
    <ComboBoxItem Content="Response Code"/>
    <ComboBoxItem Content="Method"/>
</ComboBox>
<ComboBox Name="Operator_ComboBox" HorizontalAlignment="Left" Margin="120,0,0,10.255" VerticalAlignment="Bottom" Height="22" Width="80">
    <ComboBoxItem Content="Like"/>
    <ComboBoxItem Content="Not Like"/>
</ComboBox>
<TextBox Name="Filter_TextBox" HorizontalAlignment="Left" Margin="210,0,0,10.255" TextWrapping="NoWrap" VerticalAlignment="Bottom" Width="319" Height="22"/>
</Grid>
</Window>

XML code

**Comment by Kinnara** [comment]
Thank you for your kind words and the detailed report. I'll look into this when I come back from the trip on Sunday night.

**Comment by shankarsan93** [comment]
Thanks for looking into this so quickly. Since you have closed this issue I believe you have managed to resolve it. But I couldn't see it being released yet.

Please forgive me, but I'm not a full-time programmer and hence not very sure about how to clone your project and compile it to the ModernWpf.dll file. If you don't mind, could you please give me a quick step-by-step instruction to build it myself ?

Or else, if you will be releasing it with the new fixes soon, then no worries.

I am building a gui tool for my organization and wanted to use your DLLs as I really love their look and feel. So thought of holding back my development till this gets fixed.

Thanks again for looking into this issue so quickly. Much appreciated.

**Comment by Kinnara** [comment]
A new version that contains a fix for this issue has been released.

**Comment by danielkornev** [comment]
issue remains in 0.9.6 for me :( WPF on NET 6.0
